- .talismanrc
- packages/frontend-usagers/src/pages/demande-sejour/liste.vue
- pg/scripts/02/02-4-front-init.sql
L'historique doit renseigner le user qui en est a l'origine. Comme le user peut etre soit un user USAGER, soit un user BO, pour pouvoir faire les bonnes références, on créee deux colonnes nullable correspondant au type de user.
> feat: #50 create an history table for demandes

- packages/backend/src/controllers/demandeSejour/getByDepartementCodes.js
- packages/backend/src/controllers/demandeSejour/index.js
- packages/backend/src/routes/sejour.js
- packages/backend/src/services/DemandeSejour.js
Close jira 170
- Je met le filtre directement dans la requete car celle ci ne concerne que le BO et a priori, le BO n'aura jamais accès aux demandes en brouillon
- j'en ai profité pour faire un peu de renaming sur la requete qui n'est plus vraiment en getByAdminId
> fix: Ne pas afficher les demandes en brouillon

- packages/backend/src/schemas/hebergement.js
- packages/frontend-bo/src/utils/display-input.js
- packages/frontend-usagers/src/components/DS/fiche-annexe.vue
- packages/frontend-usagers/src/components/DS/hebergements-sejour-detail.vue
- packages/frontend-usagers/src/components/hebergement.vue
- packages/frontend-usagers/src/utils/hebergementUtils.js
close jira 106 (https://jira-mcas.atlassian.net/browse/VAO-106?atlOrigin=eyJpIjoiZTUxMzU3ZjIzNTFmNDA0Nzg5NzczZmI4Zjg1YjFjZDgiLCJwIjoiaiJ9)
J'ai vérifié qu'enlever l'option "Non renseigné" ne casserait aucun display
> FIX: #106 FUsager - Fiche Hebergement - Options Accessibilité

- packages/frontend-usagers/src/components/organisme/agrement.vue
- packages/frontend-usagers/src/components/organisme/informations-generales.vue
- packages/frontend-usagers/src/components/organisme/personne-morale.vue
- packages/frontend-usagers/src/components/organisme/personne-physique.vue
- packages/frontend-usagers/src/components/protocole-sanitaire.vue
- packages/frontend-usagers/src/components/protocole-transport.vue
close jira 228 (https://jira-mcas.atlassian.net/browse/VAO-228?atlOrigin=eyJpIjoiNzQ4YWJjYzZlNGM2NDI2ZjgxODA5ODk4NDUxMjBmMzIiLCJwIjoiaiJ9)
Les deux champs “nom d’usage” ne sont pas traités ici car il n’y a pas de champs nom de naissance. il faut remplacer ce champs par nom de naissance et en créer un autre optionnel nom d’usage. Ce sera l’objet du ticket https://jira-mcas.atlassian.net/browse/VAO-273?atlOrigin=eyJpIjoiMWJlZTM2YTQ3ZmJjNGM1MTg5MmYxYThmZTQ4ZDc5ZGYiLCJwIjoiaiJ9
screenshot pour le texte introcductif et les 4 champs optionnel (moi les nom d’usage, voir remarque précédente, moins la remarque sur la recuperation des etablissement secondaires sur lesquels on a pas la main)
> feat: ajout des champs optionnel pour la création de l'organisme

- packages/backend/src/schemas/hebergement.js
- packages/frontend-usagers/src/utils/hebergementUtils.js
Ajout du message en français pour ne pas avoir de message pas défaut dans les champs de type mail au niveau du yup hébergement(s)
> fix(hebergement): 289-surcharge message d'erreur par défaut

- packages/backend/src/controllers/siret/get.js
- packages/frontend-usagers/src/components/organisme/personne-morale.vue
- Ajout d’un correctif sur la pagination des établissements secondaires
- Suppression du filtrage sur les établissements secondaires Fermés
- Ajout d’une colonne “Etat” avec “En activité” ou “Fermé”
- Si un établissement est “Fermé” il ne peut alors pas être activé
- Si un établissement fermé a été activé alors il peut être désactivé (il ne pourra plus être activé)
- Ajout Dénomination dans l'établissement secondaire
> fix(organisme): 109 ajout infos etablissements secondaire

- packages/backend/src/services/DemandeSejour.js
Close jira 372 (https://jira-mcas.atlassian.net/browse/VAO-372?atlOrigin=eyJpIjoiYjE0ZTc5NGY2ODg1NGM1OWI3NDFkZjY4MThjNTU5ODMiLCJwIjoiaiJ9)
Ce que j'ai fait : 
- la gestion des params dans `pool.query`pouvait poser porbleme : pas d'appel, mutation des params au sein d'un fonction
- le calcul du champs `estInstructeurPrincipal`ertait cassé et empechait un instructeuir principal de valider ou demander des complements sur un demande. De meme le filtre sur ce param etait cassé
> fix(bo-DS): reparation de la requete get+ filtres #372

- packages/backend/src/controllers/bo-authentication/email/login.js
- packages/backend/src/controllers/bo-user/create.js
- packages/backend/src/controllers/bo-user/index.js
- packages/backend/src/controllers/bo-user/service-competence.js
- packages/backend/src/controllers/bo-user/update.js
- packages/backend/src/helpers/bo-competence.js
- packages/backend/src/routes/bo-user.js
- packages/frontend-bo/src/pages/comptes/[[userId]].vue
- packages/frontend-bo/src/utils/serviceCompetenceOptions.js
Ticket #357
Restriction de la création des comptes en fonction de sa zone géographique
- Compétence NAT : Peut créer du NAT, REG et DEP
- Compétence REG : Peut créer du REG ou DEP
- Compétence DEP : Ne peut créer que du DEP
Implémentation frontend et backend
Déplacement ergonomique pour remonter la zone de compétence sur la création et mise à jour des comptes
> feat(comptes-bo): 357 Restriction du périmètre géo création comptes BO

- packages/frontend-usagers/src/components/DS/prestataires.vue
- packages/frontend-usagers/src/components/utils/TableFull.vue
Pour les prestaires de restauration : 
Mise à blanc de la date de naissance pour les types “personne morale”
Transverse : 
Ajout d’un ascenseur horizontal (transverse à tous les tableaux) en cas de dépassement de la largeur max des colonnes (texte long sans espace)
> fix(ds8j): prestaire-datenaiss-ascenseur-h-332

- packages/backend/src/controllers/demandeSejour/depose.js
- packages/backend/src/controllers/demandeSejour/enregistrementDemande2Mois.js
- packages/backend/src/services/pdf/ARdeclaration8jours/generate.js
- Génération des AR uniquement à la validation par le service de la déclaration #vao-418
- Ajout de _8J dans le nom du fichier pour les AR 8J pour avoir des noms uniques 2M et 8J
- Suppression de la génération de l'AR 8J à la dépose.
> fix(AR-2M-8J): génération des AR uniquement à la validation #vao-418

- packages/backend/src/config.js
- packages/backend/src/utils/mail.js
- packages/frontend-bo/src/components/connexion/email/validateToken.client.vue
close jira 379 (https://jira-mcas.atlassian.net/browse/VAO-379?atlOrigin=eyJpIjoiZjRmMzdkZGE0YzUwNDA5MDhjZTRjMTI1M2I5YmQxYzAiLCJwIjoiaiJ9).
La logique de regénération du token existait deja, mais ne fonctionnait pas : 
Le watch du composant `validate-token`n'était pas trigger avec les erreurs pour un raison inconnue. Surement un probleme avec nuxt au mount du composant. j'ai changé et utilisé les callbacks de usefetch pour arriver au meme principe.
https://www.loom.com/share/09db286d1d284046978aba0059c3aae3?sid=4eb1c989-d834-457d-a206-dadda53cd2b4
> feat(BO-auth): possibilite de regenerer un token

- packages/backend/src/controllers/demandeSejour/cancel.js
- packages/backend/src/controllers/demandeSejour/copy.js
- packages/backend/src/controllers/demandeSejour/index.js
- packages/backend/src/helpers/ds-statuts.js
- packages/backend/src/routes/sejour.js
- packages/backend/src/services/DemandeSejour.js
- packages/backend/src/utils/mail.js
- packages/frontend-bo/src/utils/demandes-sejours.js
- packages/frontend-usagers/src/pages/demande-sejour/liste.vue
- packages/frontend-usagers/src/plugins/vue-dsfr.js
- packages/frontend-usagers/src/utils/DeclarationSejour.js
- packages/migrations/src/migrations/20240701170532_both__add_enum__annule.js
Ajout fonctionnalité d'annulation d'une DS
BACK 
- Ajout du statut "ANNULEE"
FRONT USAGER (Liste des déclarations)
- Ajout d'un bouton pour annuler une DS (mutualisé avec le bouton de suppression) sur la liste des déclarations
- Ajout du statut "ANNULEE" dans les filtres de la liste des déclarations
- Envoie de mail à la DDETS
- Envoie de mail à l'organisateur
FRONT BO  (Liste des déclarations)
- Ajout du statut "ANNULEE" dans les filtres de la liste des demandes
> feat(declaration_sejour): annulation d'une DS #367 #452 #453 #454

- packages/frontend-bo/src/components/demandes-sejour/DisplayTypePrecision.vue
- packages/frontend-bo/src/components/demandes-sejour/liste.vue
- packages/frontend-bo/src/pages/comptes/liste-organisme.vue
- packages/frontend-bo/src/pages/organismes/[[organismeId]].vue
- packages/frontend-bo/src/pages/organismes/liste.vue
- packages/frontend-bo/src/pages/sejours/index.vue
- packages/frontend-usagers/src/components/DS/DisplayTypePrecision.vue
444 : Dans l’historique d’une déclaration, les dates sont manquantes car le tableau se décale au delà de la zone visible
493 : Sur le BackOffice en intégration et en préprod lorsqu’on clique sur “Action” pour filtrer il y’a une erreur qui apparait et le filtre ne renvoi pas les résultats attendus
516 :  tous les utilisateurs back office devraient avoir la visibilité des comptes des organisateurs (liste + détail). C’est apparemment limité et il n’y a aucune raison à cela
505 : typo
> fix : divers

- packages/backend/src/controllers/bo-authentication/email/forgotten-password.js
- packages/backend/src/controllers/bo-user/update.js
- packages/backend/src/schemas/bo-user.js
- packages/backend/src/services/BoUser.js
- packages/backend/src/services/DemandeSejour.js
- packages/frontend-bo/src/composables/useMenuNavItem.js
- packages/frontend-bo/src/pages/comptes/[[userId]].vue
- packages/frontend-bo/src/pages/comptes/liste.vue
- packages/migrations/src/migrations/20240711144251_back.roles__insert_desactivation.js
- Ajout du droit de désactivation d'un compte
- Le droit par défaut est a attribué à l'ensemble des profils Nationaux
- Si le droit n'est pas attribué alors l'utilisateur ne peut ni attribuer le droit ni désactiver des comptes
- Lorsque l'utilisateur a le droit de désactiver les comptes, il peut également attribuer le droit de désactivation.
- La date de désactivation est affiché au chargement de la fiche utilisateur
- Ajout d'un filtre "compte actif" dans la liste des utilisateurs BO
Un compte désactivé :
* N'est plus modifiable
* Ne peut plus se connecter 
* Ne reçoit plus de mail lors d'une réintialisation de mot de passe
* Ne peut plus utiliser un lien d'activation de compte ou changement de mot de passe.
> feat(users-BO): desactivation compte users BO #342

- packages/frontend-usagers/src/components/DS/personnel.vue
- packages/frontend-usagers/src/components/personne.vue
* Déplacement de la case “oui je certifie qu’il n’a pas de casier” au niveau global pour les personnels et accompagnants.
* Quel que soit le système d'ajout du personnel ou encadrant, la transmission de la déclaration ne sera pas possible si la case n'est pas cochée. Le personnel et/ou encadrant seront alors "incomplet"
> feat(personne): deplacement case à cocher 564

- packages/backend/src/services/DemandeSejour.js
Ajout d'un tri par défaut sur la date de modification des déclarations de séjour
- BO
- FUsager
nb : Il faudra faire pour le get de declaration_sejour la la même chose que pour les autres, c-a-d passer par un param avec les paramètres { limit, offset, sortBy, sortDirection, search }
ça n'a pas été fait pas défaut et nécessite plus de temps pour l'implémentation. Donc dans l'immédiat le ORDER BY est mis directement dans la Query au niveau du service.
> fix(liste-decla-sejour): tri par défaut #536

- packages/frontend-bo/src/components/user/Compte.vue
- packages/frontend-bo/src/stores/user.js
- Correction de la liste vide (département lors de la création des comptes)
- Correction de la mauvaise interprétation d'une compétence départemental en compétence régionale
- Correction d'affichage de la région et département lorsque le compte est en lecture seule est que l'on était hors du service de compétence.
> fix(bo-comptes): correction création de comptes 640

- packages/frontend-bo/src/components/demandes-sejour/liste.vue
- packages/frontend-bo/src/pages/messagerie/index.vue
- packages/frontend-bo/src/pages/organismes/[[organismeId]].vue
- packages/frontend-bo/src/pages/sejours/[declarationId].vue
- packages/frontend-bo/src/pages/sejours/index.vue
- packages/frontend-usagers/src/pages/demande-sejour/liste.vue
- packages/frontend-usagers/src/pages/messagerie/index.vue
- packages/shared/src/components/messages/MessageEtat.vue
- packages/shared/src/components/messages/MessageHover.vue
- packages/shared/src/utils/index.js
- Correction prévisualisation (+icone enveloppe) : lié à suppression du div dans le composant et probablement rebase de l'index.js côté shared
- Ajout affichage des cartes uniquement pour profil DREETS
- Ajout du tag de lecture uniquement pour le profil DREETS 
- Correction liste des déclarations au lieu de la liste des messages sur l’organisme (effet de bord de la mise en composant de la liste)
> fix(messagerie): correction pb composant ToolTip et autres

- packages/frontend-usagers/src/components/DS/personnel.vue
Correction des fonctions des personnels et envadrants vides dans les tableaux FO
> fix(FOPersonnel): fonctions vides dans tableau 656

- packages/backend/src/services/DemandeSejour.js
- packages/frontend-bo/src/components/demandes-sejour/liste.vue
Correction des listes vides lorsqu'il y a plus de 10 sejours
=> Le filtrage était réalisé côté front et provoquait des erreurs de pagination
Bascule du filtrage côté back
Déplacement du calcul des vignettes sur les stats côté back pour éviter les erreurs de comptage lié à la pagination
> fix(BO): correction liste message vide

- packages/backend/src/middlewares/checkPermissionBODeclarationSejour.js
Pour les users BO il n'était pas possible de remonter à l'agrément si le séjour est déclaré avec un organisateur qui n'est pas porteur de l'agrément.
Séparation en deux de la recherche de l'agrément, l'un pour le porteur l'autre pour le non porteur.
> fix(BO): ouverture déclaration pour org non porteur agrement

- packages/backend/src/services/BoUser.js
Ajout de la région dans l'export CSV des agents même pour les compétences départementales afin de permettre de filtrer par région dans le tableur.
> fix(export-bo-user): ajout de la région même pour les départements 639

- packages/backend/src/services/User.js
Fix : 
- virgule manquante sur requête recherche utilisateur
- INNER JOIN qui ne fonctionne pas lorsque l'utilisateur créé son compte car il n'est lié à aucun organisme. Il faudrait faire une requête séparée s'il y a un effet de bord
> fix(FUsager): problème de création de compte

- packages/backend/src/crons/demandes-sejours/notifyRappelActionsBO.js
Modification du lien vers les déclarations de séjour pour respecter la charte graphique. On remplace le texte par un bouton dans les deux mails.
> feat(cron): change lien vers délcaration en bouton

- packages/backend/src/schemas/organisme.js
- packages/backend/src/services/Organisme.js
- packages/frontend-usagers/src/utils/organisme.js
close jira 695 696.
Le yup etait mal ecrit pour protocole transport et protocole sanitaire dans le cas des etablissemebnt secondaires. il manquait un `shape` pour indiquer le contenu de l'objet et a la validation, les champs etaient supprimés.
Cela dit, vu avec Vincent, jusqu'a présent, la validation considérait comme optionnel la declaration des protocoles de transports et sanitaire dans le cas des organismes secondaires. Ca n'as pas de sens, on a simplifé la logique
> fix(organismes): yup pour etablissement secondaire

- packages/frontend-bo/src/pages/organismes/[[organismeId]].vue
- packages/frontend-bo/src/stores/user.js
Retrait du bouton côté Front car il n'a pas été placé dans le bon écran et ne correspond par à la demande.
Suppression dans le store également pour éviter le code mort.
L'US sera reprise au prochaine Sprint, le back sera modifié en conséquence et bouton recréé au bon endroit sur le front
> fix(bo-csv): retrait bouton extraire les comptes en CSV 632

- packages/backend/src/routes/fo-user.js
- packages/frontend-bo/src/pages/comptes/liste-organisme.vue
- packages/frontend-bo/src/stores/user.js
En remplacement du dév précédent qui avait été placé au mauvais endroit.
Ici on exporte la listes des utilisateur FUsager du côté BO.
Réutilisation des routes déjà en place en supprimant le paramètre organismeId.
> feat(bo-fusers): export csv des utilisateurs front 632

- packages/backend/src/controllers/demandeSejour/getByDepartementCodes.js
- packages/backend/src/services/DemandeSejour.js
- packages/frontend-bo/src/components/demandes-sejour/liste.vue
- packages/frontend-bo/src/pages/organismes/[[organismeId]].vue
Filtrage par siren ou siret pour la récupération des séjour (personne morales) afin de permettre de voir tous les séjours de tous les organismes principaux et secondaire lorsque c'est un organisme principal et ne voir que les séjours de l'organisme secondaire lorsque c'est un organisme secondaire
> feat(BO): change filtrage liste sejour org princ sec 670

- packages/frontend-usagers/src/components/DS/informations-generales.vue
Ajout de 2 mois à la date de déclaration par défaut car les déclarations ne peuvent être faites avant ce délais.
Date de fin modifiée également pour permettre d'être à date de début par défaut + 7 jours (total 8 jours)
> feat(fusager): sejour date par défaut +2mois 502

- packages/frontend-usagers/src/components/connexion/email/validateToken.client.vue
> fix(auth): link to connextion page when account already validated

- packages/backend/src/helpers/org-part.js
- packages/backend/src/services/Organisme.js
- packages/backend/src/services/organisme/EtablissementsSecondaires.js
- packages/backend/src/services/organisme/PersonneMorale.js
- packages/backend/src/services/organisme/PersonnePhysique.js
- packages/frontend-bo/src/components/demandes-sejour/eigs.vue
- packages/frontend-usagers/src/components/DS/informations-generales.vue
- packages/frontend-usagers/src/components/DS/menu-demande-sejour.vue
- packages/frontend-usagers/src/components/DS/stepper.vue
- packages/frontend-usagers/src/components/organisme/etablissements-secondaires.vue
- packages/frontend-usagers/src/components/organisme/menu-organisme.vue
- packages/frontend-usagers/src/components/organisme/personne-morale.vue
- packages/frontend-usagers/src/components/organisme/stepper.vue
- packages/frontend-usagers/src/components/organisme/synthese.vue
- packages/frontend-usagers/src/pages/organisme/[[organismeId]].vue
- packages/frontend-usagers/src/stores/organisme.js
- packages/frontend-usagers/src/utils/organisme.js
- packages/frontend-usagers/src/utils/organismeMenus.js
- packages/shared/src/components/Table/dsfrDataTabeV2/DsfrPaginationV2.vue
close jira 674
https://www.loom.com/share/52f6c59e9c984b59b871461fb7bcc7d7
> feat(fo-organismes): new tab for etablissements secondaires

- packages/backend/src/helpers/__tests__/queryParams.test.js
- packages/backend/src/helpers/queryParams.js
- packages/backend/src/services/DemandeSejour.js
- packages/backend/src/services/hebergement/Hebergement.js
- packages/frontend-bo/src/components/demandes-sejour/DefaultTable.vue
Close #830 #833
fix de deux bug (cf jira). J'ai ajouté un fix pour l tri sur le nom des hebergement qui ne marchait pas.
De plus, l'utilisation de `sort by LOWER(<var>)` ne fonctionnait pas si `<var>`pas de type `varchar` => cast
> fix: various bugs

- packages/backend/src/services/hebergement/Hebergement.js
- packages/frontend-usagers/src/components/DS/hebergements-sejour.vue
Close #
tickets liés : https://jira-mcas.atlassian.net/browse/VAO-835
Sur la liste des hébergements proposés dans une DS FUsager
- Ajout d'une limite "infinie"car par défaut il propose les 10 premiers
- Ajout d'un tri par nom
- Correction de la prise en compte du statut actif pour le filtrage
- [NA] Des tests ont été écrits pour tous les endpoints créés ou modifiés
- [NA] Refacto "à la volée" des parties sur lesquelles j'ai codée
> fix(fusager): DS ajout liste hébergement sans limite avec statut actif

- packages/backend/src/controllers/siret/get.js
- packages/frontend-usagers/src/components/organisme/personne-morale.vue
tickets liés : 847
Contrôle sur le fait que l'établissement ne soit pas administrativement fermé lors de la récupération des informations au niveau de l'API Insee lors de la création d'une nouvelle personne morale.
- [] Des tests ont été écrits pour tous les endpoints créés ou modifiés
- [] Refacto "à la volée" des parties sur lesquelles j'ai codée
> feat(fusager): interdiction de récupérer un siret fermé 847

- packages/frontend-usagers/src/components/demande-sejour/table.vue
Regression sur la mise à jour DSFR : oubli sur la liste des déclaration de séjour. Effet de bord : disparition des boutons
Branch concernée : feat/improve-DataTable
> fix(fusager): display button list decla sejours

- packages/backend/src/services/Organisme.js
tickets liés : VAO-870
Correction de la non récupération des données nécessaires à l'affichage de l'organisme sur la fonction getOne suite à refacto.
Erreur uniquement côté BO.
- [] Des tests ont été écrits pour tous les endpoints créés ou modifiés
- [] Refacto "à la volée" des parties sur lesquelles j'ai codée
> fix(bo): accès fiche organisme suite à refacto

- packages/frontend-usagers/src/components/DS/prestataires.vue
tickets liés : 891
Lors de la mise à jour des prestataires sur une DS 8J, la ligne se multipliait par 3 (2 identique à celle d'origine + 1 nouvelle)
Mise en place de la correction identique à celle mise sur les personnes en ajoutant un id dans la liste des prestataires.
> fix(fusager): DS multiplication prestataire updated 891

- packages/frontend-usagers/src/utils/DeclarationSejour.js
724 
Fix du contrôle sur la date de début qui bloque la mise à jour. La date n'est pas modifié, on fait sauter les contrôle pour ne pas bloquer les autres mises à jour.
> fix(fusager): suppr controle date début séjour en cours 724

- packages/frontend-bo/src/pages/connexion/index.vue
Problème d'affichage du menu Validation des comptes OVA côté BO
Chargement du profil dès la connexion pour éviter d'avoir à faire un refresh du navigateur.
> fix(bo) display menu validation ova after connect

- packages/backend/src/utils/mail.js
Suppression des liens inutiles du lien "connexion VAO" alors que c'est un cas de refus. C'est contradictoire
Vu avec la MOA.
> fix(account) suppression lien vao message refus

- packages/frontend-bo/src/pages/sejours/[declarationId].vue
- packages/frontend-bo/src/pages/sejours/[declarationId]/messagerie.vue
- packages/shared/src/components/DsfrTabsItemV2.vue
- packages/shared/src/components/DsfrTabsV2.vue
Close #
tickets liés : [fix/chat-message-indication-922](https://jira-mcas.atlassian.net/jira/software/c/projects/VAO/boards/336/backlog?selectedIssue=VAO-922)
Ajoute le nombre de messages non lus + une icone dans le label de l'onglet "messagerie" sur l'écran d'une déclaration de séjour coté BO
> fix(bo): affichage volume de message reçu et icone dans le tab

- packages/frontend-usagers/src/components/demande-sejour/table.vue
989
On désactive le bouton Supprimer lorsque ce n'est pas mon établissement (donc les établissements secondaires)
La désactivation n'était déjà pas possible (déjà contrôlé côté backend) il s'agissait juste de griser le bouton.
> feat(fusager): désactivation bouton supprimé pour etab secondaire 989

- packages/backend/src/middlewares/common/checkJWT.js
Deconnexion utilisateur à la rotation du token au bout de 30 minutes
Potentiellement aléatoire
> fix(checkjwt): token not found on rotation - user deconnexion

- .talismanrc
- packages/frontend-bo/src/layouts/default.vue
- packages/frontend-usagers/src/layouts/default.vue
- packages/shared/src/components/Skiplinks.vue
- packages/shared/src/components/index.js
[fix/liens-evitement-1008](https://jira-mcas.atlassian.net/jira/software/c/projects/VAO/boards/336/backlog?selectedIssue=VAO-1008)
Fais en sorte d'avoir les liens d'evitement sur toutes les pages. Actuellement le focus ne se reset pas quand on change de page
> fix: liens evitements fonctionnels sur toutes les pages(1008)

- .talismanrc
- packages/backend/src/controllers/fo-user/list.js
- packages/backend/src/helpers/queryParams.js
- packages/backend/src/services/FoUser.js
- packages/frontend-bo/src/pages/comptes/liste-organisme.vue
https://jira-mcas.atlassian.net/jira/software/c/projects/VAO/boards/336?selectedIssue=VAO-1088
Correction du tri tableau de la liste des comptes organisateurs. Refactoring du service lié en utilisant le helper processQuery. En front suppression du debounce sur le tri des tableaux. Le debounce est conservé uniquement pour les filtres sous la forme de text inputs.
J'ai galéré avec le GROUP BY qui s'appliquait avant les filtres ajoutés. Du coup en l'état je gère le GROUP BY dans le service. Est ce que ça serait mieux de modifier le helper "processQuery" pour qu'il prenne un param groupBy et qu'il l'ajoute au bon endroit ?
> fix: tri des tableau liste comptes organisateurs (1088)

- packages/backend/src/helpers/__tests__/queryParams.test.js
- packages/backend/src/helpers/queryParams.js
- packages/backend/src/services/Territoire.js
1111
Mise en place d'un tri par défaut sur le label pour les territoires
Correction de la fonction getSort qui ne prennait pas le tri par défaut
> fix(bo): default sort correction 1111

- packages/backend/src/helpers/queryParams.js
Aucun
Régression sur le tri des listes par défaut suis à review. 
La liste restait vide pour la déclaration des séjours côté BO
> fix(ds): fo empty list
