.talismanrc, packages/frontend-usagers/src/components/DS/informations-personnel.vue, packages/frontend-usagers/src/components/DS/informations-vacanciers.vue, packages/frontend-usagers/src/components/DS/projet-sejour.vue, packages/frontend-usagers/src/components/operateur/agrement-read-only.vue, packages/frontend-usagers/src/components/operateur/agrement.vue, packages/frontend-usagers/src/components/operateur/personne-morale-read-only.vue, packages/frontend-usagers/src/components/operateur/personne-morale.vue, packages/frontend-usagers/src/components/operateur/personne-physique-read-only.vue, packages/frontend-usagers/src/components/operateur/personne-physique.vue, packages/frontend-usagers/src/components/personne.vue, packages/frontend-usagers/src/components/personnes.vue, packages/frontend-usagers/src/components/protocole-sanitaire.vue, packages/frontend-usagers/src/components/protocole-transport-read-only.vue, packages/frontend-usagers/src/components/protocole-transport.vue, packages/frontend-usagers/src/components/search-address.vue, packages/frontend-usagers/src/pages/connexion/enregistrement.vue, packages/frontend-usagers/src/pages/connexion/mot-de-passe-oublie.vue, packages/frontend-usagers/src/pages/connexion/reset-mot-de-passe.vue, packages/frontend-usagers/src/utils/adresse.js, packages/frontend-usagers/src/utils/organisme.js, packages/frontend-usagers/src/utils/personne.js, packages/frontend-usagers/src/utils/protocoleSanitaire.js, packages/frontend-usagers/src/utils/protocoleTransport.js, packages/frontend-usagers/src/utils/regex.js
Les regex utilisées dans la création de compte et la fiche organisme sont externalisées dans utils/regex
Les schémas de la fiche organisme sont dans utils/organisme, tout comme les valeurs de liste.
=> Refactor 77 centralize schema infos

.talismanrc, packages/backend/src/controllers/demandeSejour/getByIdBo.js, packages/backend/src/controllers/demandeSejour/index.js, packages/backend/src/routes/documents.js, packages/backend/src/routes/hebergement.js, packages/backend/src/routes/sejour.js, packages/backend/src/services/DemandeSejour.js, packages/frontend-bo/src/assets/css/main.css, packages/frontend-bo/src/components/demandes-sejour/Declaration.vue, packages/frontend-bo/src/components/demandes-sejour/DemandeStatusBadge.vue, packages/frontend-bo/src/components/demandes-sejour/Details.vue, packages/frontend-bo/src/components/demandes-sejour/DisplayFormulaire.vue, packages/frontend-bo/src/components/demandes-sejour/DisplayInput.vue, packages/frontend-bo/src/components/demandes-sejour/DisplayPj.vue, packages/frontend-bo/src/components/utils/Table.vue, packages/frontend-bo/src/pages/sejours/[demandeId].vue, packages/frontend-bo/src/pages/sejours/index.vue, packages/frontend-bo/src/stores/demande-sejour.js, packages/frontend-bo/src/utils/demandes-sejours.js, packages/frontend-bo/src/utils/display-input.js, packages/frontend-usagers/src/components/protocole-sanitaire-read-only.vue
https://www.loom.com/share/eba20cb9f4c54a5681a6bee04c1b8129?sid=5c56a237-be1d-4951-b1d0-27dca94a3f07
=> #29 visualisation d'une demande se séjour

packages/backend/src/controllers/demandeSejour/get.js, packages/backend/src/controllers/demandeSejour/post.js, packages/frontend-bo/src/components/demandes-sejour/Details.vue, packages/frontend-bo/src/helpers/menuNavItem.js, packages/frontend-usagers/src/utils/menuNavItems.js
=> FIX: demande devient déclaration

packages/frontend-bo/src/pages/sejours/[demandeId].vue
=> fix: proteger l'affichage d'une demande

packages/frontend-bo/src/pages/sejours/[demandeId].vue
=> fix: enlever le tyab historique

packages/frontend-usagers/src/components/DS/hebergements-sejour-detail.vue
=> fix: correct DsfrCheckboxSet bad props

packages/frontend-bo/src/utils/display-input.js, packages/frontend-usagers/src/components/organisme/personne-physique.vue, packages/frontend-usagers/src/utils/organismeMenus.js
=> fix: FUsager_Fiche organisateur_ renseignements généraux-personne-physique

packages/frontend-usagers/src/components/protocole-sanitaire.vue
close jira 101 (https://jira-mcas.atlassian.net/browse/VAO-101?atlOrigin=eyJpIjoiOGE5NDg4YWM4ZDRiNGM2NGIwOTZiMzQyZGU3ZDQwYTgiLCJwIjoiaiJ9)
=> fix: #101 FUsager - Fiche Organisateur - Informations sanitaires - Bloc PJ

packages/frontend-usagers/src/layouts/default.vue
close jira 171 (https://jira-mcas.atlassian.net/browse/VAO-171?atlOrigin=eyJpIjoiYWYyN2MzN2Q1ODYyNDdhOGE0NzRlMzlkY2NlYTM2MGEiLCJwIjoiaiJ9)
=> FIX: Titre à harmoniser Front office_ back office

packages/frontend-bo/src/layouts/default.vue, packages/frontend-usagers/src/layouts/default.vue, packages/frontend-usagers/src/pages/connexion/index.vue
close jira 166 (https://jira-mcas.atlassian.net/browse/VAO-166?atlOrigin=eyJpIjoiZWMwNjI0Yjk5YzU0NDgzMmFhYTVlYWM1OWJiOTJmMjgiLCJwIjoiaiJ9)
=> fix: Page de connexion - ne pas afficher le menu tant qu'on n'est pas connecté

packages/backend/src/schemas/declaration-sejour.js, packages/backend/src/schemas/hebergement.js, packages/frontend-bo/src/utils/display-input.js
close jira 218 (https://jira-mcas.atlassian.net/browse/VAO-218?atlOrigin=eyJpIjoiZjlmODE5YjBiNmY2NDMyYjgwMDgyMjVlMjJkZTFlNzkiLCJwIjoiaiJ9)
=> FbackOffice : Les demandes de sejour validées ne sont plus liées a une adresse

packages/backend/src/controllers/demandeSejour/depose.js
close jira  206 (https://jira-mcas.atlassian.net/browse/VAO-206?atlOrigin=eyJpIjoiMDBlYzRmN2UzMmU2NDQ4YTg2OTliN2E2OGUzOWEzOTMiLCJwIjoiaiJ9)
A vu des tickets suivant, la partie envoie de mail n'est pas prise en charge ici.
- https://jira-mcas.atlassian.net/browse/VAO-241
- https://jira-mcas.atlassian.net/browse/VAO-242
Le reste du ticket etait en fait deja implementé (on pouvait deja modifier une demande dont le statut est a completer. J'ai juste modifié le message de l'historique dans ce cas ("ajout de complément" au lieu de "depose a 2 mois")
=> feat: #206 une orga peut completer une demande

packages/backend/src/controllers/demandeSejour/depose.js, packages/backend/src/controllers/organisme/finalize.js, packages/backend/src/schemas/organisme.js, packages/backend/src/services/DemandeSejour.js, packages/backend/src/services/Organisme.js, packages/backend/src/utils/mail.js, packages/frontend-bo/nuxt.config.ts, packages/frontend-usagers/nuxt.config.ts, packages/frontend-usagers/src/components/organisme/agrement.vue, packages/frontend-usagers/src/components/organisme/synthese.vue, packages/frontend-usagers/src/components/protocole-sanitaire.vue, packages/frontend-usagers/src/utils/organisme.js
fix 236 : L’organisme est déjà présent en base => utilisateur bloqué
fix 224 : pb de téléphone responsable de sejour
feat 241 et 242 : envoi des mails aux users back
=> fix: 236/224 et feat 241/242

packages/backend/src/schemas/declaration-sejour.js, packages/backend/src/schemas/hebergement.js, packages/frontend-usagers/src/components/DS/hebergements-sejour-detail.vue, packages/frontend-usagers/src/components/DS/hebergements-sejour.vue, packages/frontend-usagers/src/components/DS/synthese.vue, packages/frontend-usagers/src/pages/hebergements/[[hebergementId]].vue, packages/frontend-usagers/src/stores/hebergement.js, packages/frontend-usagers/src/utils/DeclarationSejour.js, packages/frontend-usagers/src/utils/hebergementUtils.js
close jira 259 (https://jira-mcas.atlassian.net/browse/VAO-259?atlOrigin=eyJpIjoiODUyZWU2NzFmZWE0NDVjOThhMTI4MWIxYzE2ZDc5YjMiLCJwIjoiaiJ9)
https://www.loom.com/share/ea358ce13b9e44ea828ff66af025e203?sid=33a324ca-8023-4282-90ae-1f61ae437db8
En plus de la fiche, il ty avait un bug lors de la créationd d'un hebergement a partir de la demande  de séjour : la logie d'upload des ticket n'avait pas été mise dans la fonction save de la modale. J'ai factorisée cette logique en un seul point : dans le store hebergement car elle est appelée a 3 endroits.
=> feat : #259 FUsager_ Création lieu d'hébergement_ ERP et PJ

packages/frontend-usagers/src/pages/organisme/[[organismeId]].vue
close jira 76 https://jira-mcas.atlassian.net/browse/VAO-76?atlOrigin=eyJpIjoiODc2M2U4ZGU3ZjEzNDM2NDkyOGE4NTMwOWU3MWFlYTUiLCJwIjoiaiJ9
=> feat: typo sur Agrément sauvegardé

packages/frontend-bo/src/layouts/default.vue, packages/frontend-usagers/src/layouts/default.vue
close jira 219 (https://jira-mcas.atlassian.net/browse/VAO-219?atlOrigin=eyJpIjoiYjdlMTI0MDg5NzNlNDI0M2EyZjZkZmI0NmNlNjJlOGEiLCJwIjoiaiJ9) 
et jira 269 https://jira-mcas.atlassian.net/browse/VAO-269?atlOrigin=eyJpIjoiNzA2NmI1YTUzYmUxNDQzOThhYjBjNmIzZGY1ZTQzOTYiLCJwIjoiaiJ9
=> feat: texte pied de page

packages/backend/src/schemas/hebergement.js, packages/frontend-usagers/src/components/hebergement.vue, packages/frontend-usagers/src/components/organisme/agrement.vue, packages/frontend-usagers/src/pages/hebergements/[[hebergementId]].vue, packages/frontend-usagers/src/utils/hebergementUtils.js
close jira 239 (https://jira-mcas.atlassian.net/browse/VAO-239?atlOrigin=eyJpIjoiMjU0MDYwM2UyNzVkNDQ4Mzg0YmU2M2VhZGJjYThjZDAiLCJwIjoiaiJ9)
https://www.loom.com/share/60535ab46100445d910be53eaaa49701?sid=08c34799-6f37-4d42-96bb-214d1e321512
=> feat: champs optionnel dans hebergements

packages/frontend-usagers/src/pages/organisme/[[organismeId]].vue
close jira 243 (https://jira-mcas.atlassian.net/browse/VAO-243?atlOrigin=eyJpIjoiOGE3NWQwYWQ0MjljNDI2MmJkOWZlNzgxMGJlZTA1OTQiLCJwIjoiaiJ9)
=> feat: FUsager_ Fiche organisateur_ Agrément_ - Ajout de Fichier en PJ

packages/frontend-usagers/src/components/protocole-transport.vue
close jira 233 (https://jira-mcas.atlassian.net/browse/VAO-244?atlOrigin=eyJpIjoiNmMyZTQ4NWNiNjZiNDRkMGJhNDYzODZkN2E2N2Y1MWUiLCJwIjoiaiJ9)
=> feat: wording PJ dans la partie transport du formulaire organisateur

packages/frontend-bo/src/pages/footer/accessibilite.vue, packages/frontend-bo/src/pages/footer/donnees-personnelles.vue, packages/frontend-bo/src/pages/footer/mentions-legales.vue
Mise à jour des pages du footer
Page donnees-personnelles
Page mentions-legales
Page accessibilite
=> feat(fbackoffice): 282 mise à jours des pages du footer

.talismanrc, packages/frontend-usagers/src/components/organisme/personne-morale.vue, packages/frontend-usagers/src/components/personnes.vue
Close jira 240 (https://jira-mcas.atlassian.net/browse/VAO-240?atlOrigin=eyJpIjoiOTJmMWZhYmUxMzQxNDU2YWI2M2M1ODg5N2ZiYTM1ZjYiLCJwIjoiaiJ9)
https://www.loom.com/share/522cbc6a33304f708653549ca9946172?sid=746fcc77-ae7b-4dfd-9cf8-00181fa16e0b
=> feat: pagination dans les tableaux

.talismanrc, packages/backend/src/utils/regex.js, packages/frontend-bo/src/pages/connexion/reset-mot-de-passe.vue, packages/frontend-bo/src/utils/regex.js, packages/frontend-usagers/src/utils/regex.js
Close jira 287 (https://jira-mcas.atlassian.net/browse/VAO-287?atlOrigin=eyJpIjoiODJiMTA4MGE4ZTdmNGU5Nzg1YmQwNjU1YjIyNzhlYjQiLCJwIjoiaiJ9)
=> feat: new regex for special characters

packages/frontend-usagers/src/components/DS/hebergements-sejour-detail.vue, packages/frontend-usagers/src/components/hebergement.vue
- Ajout des informations ERP sur la déclaration modification d'un hébergement
- Ajout des informations ERP sur la modification des hébergements d'un séjour
- Déplacement des informations ERP sur l'écran d'hébergement d'un séjour
=> feat(hebergement): 293 Ajout info ERP sur nouvel hébergement et

packages/backend/src/schemas/parts/projet-sejour.js, packages/backend/src/services/pdf/declaration2mois/parts/ProjetSejour.js, packages/frontend-bo/src/utils/display-input.js, packages/frontend-usagers/src/components/DS/projet-sejour.vue, packages/frontend-usagers/src/utils/projetSejour.js
close jira 249 (https://jira-mcas.atlassian.net/browse/VAO-249?atlOrigin=eyJpIjoiZjdmNzlmMjY1YzQxNDIzMThmNTgzYTY4ZDE4NzljMDUiLCJwIjoiaiJ9)
=> feat: ajout de 2 champs dans projet de séjour

packages/backend/src/schemas/declaration-sejour.js, packages/backend/src/schemas/hebergement.js, packages/backend/src/services/pdf/declaration2mois/parts/FicheAnnexe.js, packages/backend/src/services/pdf/declaration2mois/parts/TransportHebergement.js, packages/frontend-usagers/src/components/DS/hebergements-sejour-detail.vue, packages/frontend-usagers/src/components/DS/informations-generales.vue, packages/frontend-usagers/src/components/hebergement.vue, packages/frontend-usagers/src/utils/DeclarationSejour.js, packages/frontend-usagers/src/utils/hebergementUtils.js
close jira 239 (https://jira-mcas.atlassian.net/browse/VAO-239?atlOrigin=eyJpIjoiYjgwZWFmM2Y3NTJmNDM4ZmE0ODc5NDZkZGZkODMzODciLCJwIjoiaiJ9)
=> feat: champs optionnels

packages/frontend-usagers/src/pages/index.vue
close jira 308 (https://jira-mcas.atlassian.net/browse/VAO-308?atlOrigin=eyJpIjoiZjEwYmRlZTg4OTA5NDBhNTk4ZDMwMWI2MzlmMDI0MTMiLCJwIjoiaiJ9)
=> fix: eneleve un point d'exclamation

packages/backend/src/controllers/demandeSejour/demandeComplements.js, packages/backend/src/utils/mail.js, packages/frontend-bo/src/pages/comptes/[[userId]].vue, packages/frontend-usagers/src/components/organisme/agrement.vue, packages/frontend-usagers/src/components/organisme/menu-organisme.vue, packages/frontend-usagers/src/pages/organisme/[[organismeId]].vue
close jira 300 (https://jira-mcas.atlassian.net/browse/VAO-300?atlOrigin=eyJpIjoiOThjZThmYzA5ZTZjNGYwZGJjOGZmYWI0YjhkZWFmNGIiLCJwIjoiaiJ9)
sauf point 3. qui est deja fait par ailleurs
=> fix: wording

packages/frontend-bo/src/layouts/default.vue
close jira 298 (https://jira-mcas.atlassian.net/browse/VAO-298?atlOrigin=eyJpIjoiMDQ5YjMzYjRkZDYyNDU1OWFmZWMxOGJlYzVhZDgxM2EiLCJwIjoiaiJ9)
=> fix: ajout du portail d'aide bo

packages/frontend-bo/src/pages/comptes/[[userId]].vue, packages/frontend-usagers/src/pages/connexion/enregistrement.vue
- Ajout d'un message côté front usager lors de la tentative de création d'un compte existant
- Correction wording message sur la même fonctionnalité côté BO
=> fix(fusager): 95 affichage de l'existance d'un compte à la création

packages/backend/src/controllers/siret/get.js
#118 : Remplacement null par vide sur champ adresse
=> fix(agrement): 118 remplacement null par vide sur champ adresse

packages/frontend-usagers/src/components/DS/hebergements-sejour-detail.vue, packages/frontend-usagers/src/components/hebergement.vue
close jira 310(https://jira-mcas.atlassian.net/browse/VAO-310?atlOrigin=eyJpIjoiNTYwOTM4ZDUxZmMzNGJmOTliNjNmNmFhZWNhNzZlZWEiLCJwIjoiaiJ9)
=> fix: la carte ne cache plus le champs nouvelle adresse

packages/frontend-usagers/src/components/DS/hebergements-sejour-detail.vue
close jira 301 (https://jira-mcas.atlassian.net/browse/VAO-289?atlOrigin=eyJpIjoiMTc2N2M1NGJmYTY5NDZiNjgxYTUwYzFmNjY3N2U4ZjciLCJwIjoiaiJ9)
=> fix: nombre lit superposé peut etre null depuis la demande de sejour

.talismanrc, packages/backend/src/services/DemandeSejour.js, packages/frontend-bo/src/components/demandes-sejour/DisplayFormulaire.vue, packages/frontend-bo/src/components/demandes-sejour/Documents.vue
close jira (296) https://jira-mcas.atlassian.net/browse/VAO-296?atlOrigin=eyJpIjoiMmJiZjQ3NzIwODkwNDRlMDkxYmI5NmY3MmMyYzJkMmQiLCJwIjoiaiJ9
copier collé du composant `Document`du front usager avec une legere adatpation au nom des attribus emplyé en BO
=> fix: separation des documents joins

packages/frontend-bo/nuxt.config.ts, packages/frontend-bo/package.json, packages/frontend-bo/src/components/connexion/email/validateToken.client.vue, packages/frontend-bo/src/layouts/default.vue, packages/frontend-bo/src/pages/connexion/index.vue, packages/frontend-bo/src/pages/sejours/[demandeId].vue, packages/frontend-bo/src/pages/sejours/index.vue, packages/frontend-bo/src/plugins/toaster.js, packages/frontend-bo/yarn.lock, packages/frontend-usagers/.eslintrc.json, packages/frontend-usagers/nuxt.config.ts, packages/frontend-usagers/package.json, packages/frontend-usagers/src/components/DS/hebergements-sejour-detail.vue, packages/frontend-usagers/src/components/DS/hebergements-sejour.vue, packages/frontend-usagers/src/components/connexion/email/validateToken.client.vue, packages/frontend-usagers/src/components/hebergement.vue, packages/frontend-usagers/src/components/organisme/agrement.vue, packages/frontend-usagers/src/components/organisme/personne-morale.vue, packages/frontend-usagers/src/components/protocole-sanitaire.vue, packages/frontend-usagers/src/components/protocole-transport.vue, packages/frontend-usagers/src/components/search-address.vue, packages/frontend-usagers/src/layouts/default.vue, packages/frontend-usagers/src/pages/connexion/enregistrement.vue, packages/frontend-usagers/src/pages/connexion/index.vue, packages/frontend-usagers/src/pages/demande-sejour/[[demandeId]].vue, packages/frontend-usagers/src/pages/hebergements/[[hebergementId]].vue, packages/frontend-usagers/src/pages/organisme/[[organismeId]].vue, packages/frontend-usagers/src/plugins/toaster.js, packages/frontend-usagers/yarn.lock
=> feat(accessibilité): utilisation dsfr-toaster-nuxt-module #264

packages/backend/src/services/DemandeSejour.js
=> fix(instructeur): seuls les instructeurs ayant les droits sur les dem… #320

packages/backend/src/services/BoUser.js
=> fix(Instructeurs): le raffraîchissement du token fait perdre le #355

packages/backend/src/services/DemandeSejour.js, packages/backend/src/services/pdf/declaration2mois/parts/FicheAnnexe.js, packages/frontend-usagers/src/components/DS/informations-generales.vue
close jira 366 (https://jira-mcas.atlassian.net/browse/VAO-366?atlOrigin=eyJpIjoiNTBmOTliMmE3YmM3NDY0ZWJkMWZkMDVmMjE5NjYyZDgiLCJwIjoiaiJ9)
=> fix: Erreurs dans le CERFA Généré de la DS2M

packages/frontend-bo/src/pages/footer/mentions-legales.vue, packages/frontend-usagers/src/pages/footer/mentions-legales.vue
close jira 179 https://jira-mcas.atlassian.net/browse/VAO-179?atlOrigin=eyJpIjoiNjE5MjFlM2NlNTRkNDkxZTgyMGM0ZjNhMTExYjY1NWEiLCJwIjoiaiJ9
=> fix: correction des mentions legales

packages/backend/src/schemas/parts/protocoleTransport.js
close jira 371 (https://jira-mcas.atlassian.net/browse/VAO-371?atlOrigin=eyJpIjoiYmRjOWY5YjcwODQ4NDExNmEwYzZmMjYyNTUzOGNkMWEiLCJwIjoiaiJ9)
=> fix: 371 meme validation front et back pour precisionVehiculesAdaptes

packages/backend/src/services/pdf/parts/FicheAnnexe.js
Correction de la génération du pdf avec contenant un hébergement avec une arrêté du maire
=> fix(pdf): correction erreur generation pdf arrete maire #vao-383

.talismanrc, packages/backend/src/services/DemandeSejour.js, packages/frontend-bo/src/components/demandes-sejour/DisplayFormulaire.vue, packages/frontend-bo/src/utils/demandes-sejours.js, packages/frontend-bo/src/utils/display-input.js
close jira #349 (https://jira-mcas.atlassian.net/browse/VAO-349?atlOrigin=eyJpIjoiZGY2N2JlMmI3NmNjNDU0NjlkOGU3ZDBmMWYxNjc1ZDAiLCJwIjoiaiJ9)
=> feat(DS8J-BO): display DS8J #349

packages/frontend-usagers/src/components/DS/personnel.vue, packages/frontend-usagers/src/components/personne.vue
close jiras 329 (https://jira-mcas.atlassian.net/browse/VAO-329?atlOrigin=eyJpIjoiYjkwYjE0NjdkOTI2NDUwZWJkYzZlMjNjYTQyYzk3OGQiLCJwIjoiaiJ9)
and 394 https://jira-mcas.atlassian.net/browse/VAO-394?atlOrigin=eyJpIjoiYTIwNzBmZGUwMWM5NDQzOTlmZWUyNmFhOGU5Y2RhMWIiLCJwIjoiaiJ9
=> fix(accompagnant): wording et affichage de colonne #329 #394

packages/frontend-bo/src/pages/informations/index.vue
close jria 403 https://jira-mcas.atlassian.net/browse/VAO-403?atlOrigin=eyJpIjoiZGY4MTU0YmM2ODEzNGQ1ZDlmNDJjYzFkN2UyN2I3MmYiLCJwIjoiaiJ9
=> fix(fichier-information): wording #403

packages/backend/src/controllers/demandeSejour/getByDepartementCodes.js, packages/backend/src/services/DemandeSejour.js, packages/frontend-bo/src/pages/sejours/index.vue, packages/frontend-usagers/src/pages/demande-sejour/liste.vue
close jira 396 (https://jira-mcas.atlassian.net/browse/VAO-396?atlOrigin=eyJpIjoiNDVhYWZhNTIwOTg2NDJlZGI3OGU4NzcwNDc1YTgyMjMiLCJwIjoiaiJ9)
https://www.loom.com/share/edbc4b67c35c49f3bd2e8a0ee3d95568?sid=e35a266e-e489-40b4-bddd-b85c9ff2c8c4
=> feat(BO-DS): filtre par l'id_fonctionnel #396

packages/backend/src/schemas/declaration-sejour.js, packages/frontend-usagers/src/utils/DeclarationSejour.js
close jira 397 (https://jira-mcas.atlassian.net/browse/VAO-397?atlOrigin=eyJpIjoiNWU0NDc2OGRmYTNhNDQyNWJjN2VmNmNiMDBkMDk1ZTMiLCJwIjoiaiJ9)
close sentry https://sentry.fabrique.social.gouv.fr/organizations/incubateur/issues/?environment=production&project=102&statsPeriod=14d
=> fix(post-DS): le libelle d'une DS fait au max 50 characteres

packages/backend/src/app.js, packages/backend/src/controllers/siret/get.js, packages/frontend-usagers/src/components/organisme/personne-morale.vue
… (#282)
close jira 441
(https://jira-mcas.atlassian.net/browse/VAO-441?atlOrigin=eyJpIjoiZGFkMDY1N2I0ZmNjNGVlOGExOGQzMDBmNzRiOWIxNDAiLCJwIjoiaiJ9)
=> Cherry-pick preprod sur main (jira 441)

packages/backend/src/middlewares/getDepartements.js
close jira 432 (https://jira-mcas.atlassian.net/browse/VAO-432?atlOrigin=eyJpIjoiMzU2YzJiNjQxODNhNGZmMmJjY2IzODI4MWNjMzRjNGEiLCJwIjoiaiJ9)
=> fix: ajouter les departements corses dans le middleware getDepartements

.talismanrc, packages/backend/src/controllers/authentication/email/renew-password.js
close jira 408 (https://jira-mcas.atlassian.net/browse/VAO-408?atlOrigin=eyJpIjoiNmExNmNmMTMzZDZjNDZhZWFjZTI2NGU3NzNlZGNhODIiLCJwIjoiaiJ9)
=> feat(User): validate user if editPassword

packages/frontend-usagers/src/pages/demande-sejour/[[demandeId]].vue
https://jira-mcas.atlassian.net/jira/software/c/projects/VAO/boards/336?selectedIssue=VAO-431
=> feat(demandeId): Change toaster text on save

packages/backend/src/services/pdf/parts/Sanitaire.js
https://jira-mcas.atlassian.net/jira/software/c/projects/VAO/boards/336?selectedIssue=VAO-410
=> fix(Sanitaire.js): Fix typo

packages/frontend-usagers/src/pages/demande-sejour/[[demandeId]].vue, packages/frontend-usagers/src/utils/DeclarationSejour.js
https://jira-mcas.atlassian.net/jira/software/c/projects/VAO/boards/336?selectedIssue=VAO-427
=> feat(demandeId): Display trip's details under the title

.talismanrc, packages/backend/src/controllers/bo-user/create.js, packages/backend/src/controllers/bo-user/list.js, packages/backend/src/middlewares/bo-check-terr-for-account-creation.js, packages/backend/src/routes/bo-user.js, packages/backend/src/services/BoUser.js, packages/frontend-bo/src/pages/comptes/[[userId]].vue, packages/frontend-bo/src/stores/referentiels.js, packages/frontend-bo/src/stores/user.js
close jira 
- #384 (https://jira-mcas.atlassian.net/browse/VAO-384?atlOrigin=eyJpIjoiZGM3ZmQ1ZjAzZTVjNDYwOWJhNDU3ZTBlMzI3NjFhMzUiLCJwIjoiaiJ9)
- #385 (https://jira-mcas.atlassian.net/jira/software/c/projects/VAO/boards/336?selectedIssue=VAO-385)
=> feat(BO): visibilite des comptes

packages/backend/src/middlewares/can-update-ds.js, packages/backend/src/routes/sejour.js, packages/backend/src/services/DemandeSejour.js, packages/frontend-usagers/src/components/DS/hebergements-sejour.vue, packages/frontend-usagers/src/components/DS/informations-personnel.vue, packages/frontend-usagers/src/components/DS/informations-vacanciers.vue, packages/frontend-usagers/src/components/DS/projet-sejour.vue, packages/frontend-usagers/src/components/protocole-sanitaire.vue, packages/frontend-usagers/src/components/protocole-transport.vue
close 456 (https://jira-mcas.atlassian.net/browse/VAO-456?atlOrigin=eyJpIjoiMTVhZjI3YTgxZWZjNGFhZTg0MTgzY2JjYjFmZWRhNGEiLCJwIjoiaiJ9)
Loom : https://www.loom.com/share/3074aff5fe39458f8d4d64bdde77e31d?sid=6db05eef-3830-462d-8bff-eed3ea7b43f3
=> fix(DS): protect update DS route according to statut

packages/backend/src/controllers/demandeSejour/enregistrementDemande2Mois.js, packages/backend/src/utils/mail.js
Ajout d'un mail spécifique pour la validation d'une DS8J par la DDETS
Ticket 467
=> fix(ds8j): mail à la validation BO pour ds8j #467

packages/frontend-bo/src/pages/connexion/index.vue, packages/frontend-bo/src/pages/connexion/reset-mot-de-passe.vue, packages/frontend-usagers/src/components/DS/hebergements-sejour-detail.vue, packages/frontend-usagers/src/components/hebergement.vue, packages/frontend-usagers/src/pages/connexion/enregistrement.vue, packages/frontend-usagers/src/pages/connexion/index.vue, packages/frontend-usagers/src/pages/connexion/reset-mot-de-passe.vue, packages/frontend-usagers/src/utils/cssHelper.js
https://jira-mcas.atlassian.net/jira/software/c/projects/VAO/boards/336?selectedIssue=VAO-434
=> Vao 434 rgaa accessibilit r gle 10.2

packages/backend/src/services/DemandeSejour.js, packages/frontend-bo/src/components/demandes-sejour/liste.vue
=> feat(DemandeSejour): Change filter to set on need to update or not

packages/frontend-usagers/src/components/DS/menu-demande-sejour.vue, packages/frontend-usagers/src/components/organisme/menu-organisme.vue, packages/frontend-usagers/src/pages/demande-sejour/[[demandeId]].vue, packages/frontend-usagers/src/pages/organisme/[[organismeId]].vue
https://jira-mcas.atlassian.net/jira/software/c/projects/VAO/boards/336?selectedIssue=VAO-433
=> feat(menus): Change property to better responsive

packages/frontend-usagers/src/components/organisme/personne-morale.vue
https://jira-mcas.atlassian.net/browse/VAO-440
=> feat(personne-morale.vue): Filter on etablissements availables

packages/backend/src/services/DemandeSejour.js, packages/frontend-bo/src/components/demandes-sejour/liste.vue, packages/frontend-bo/src/components/utils/CardNumber.vue, packages/frontend-bo/src/components/utils/CardsNumber.vue, packages/frontend-bo/src/stores/demande-sejour.js
https://jira-mcas.atlassian.net/browse/VAO-465
=> Vao 465 ajout d infos sur les t ches effectuer pour les agents

packages/frontend-bo/src/components/demandes-sejour/liste.vue
https://jira-mcas.atlassian.net/jira/software/c/projects/VAO/boards/336?selectedIssue=VAO-445
=> feat(liste.vue): Change order of status

packages/frontend-usagers/src/components/DS/hebergements-sejour.vue
https://jira-mcas.atlassian.net/jira/software/c/projects/VAO/boards/336?selectedIssue=VAO-430
=> Vao 430 f usager s jour itn rant coh rance des informations

packages/backend/src/controllers/demandeSejour/getExtract.js, packages/backend/src/controllers/demandeSejour/index.js, packages/backend/src/routes/sejour.js, packages/backend/src/services/DemandeSejour.js, packages/frontend-bo/src/components/demandes-sejour/liste.vue, packages/frontend-bo/src/stores/demande-sejour.js, packages/frontend-bo/src/utils/csv.js
https://jira-mcas.atlassian.net/jira/software/c/projects/VAO/boards/336?selectedIssue=VAO-449
=> Vao 449 bo pouvoir extraire les informations en csv de la liste des s jours

packages/frontend-bo/src/components/demandes-sejour/liste.vue
https://jira-mcas.atlassian.net/jira/software/c/projects/VAO/boards/336?selectedIssue=VAO-465
=> feat(liste.vue): hide some element when page is on organisme

packages/frontend-usagers/src/components/organisme/personne-morale.vue
=> feat(personne-morale.vue): add filter on autorisation

packages/frontend-bo/src/components/utils/Table.vue
=> fix: tables

packages/frontend-usagers/src/components/organisme/personne-morale.vue
=> fix(personne-morale): fix filter for status

packages/frontend-bo/src/pages/comptes/[[userId]].vue
Fix suite à l'ajout de la fonctionnalité de désactivation de compte (invalid date)
=> fix(BoUsage): pb invalid date format premiere desactivation

packages/backend/src/controllers/eig/get-by-ds-id.js, packages/backend/src/controllers/eig/index.js, packages/backend/src/controllers/eig/update.js, packages/backend/src/helpers/eig.js, packages/backend/src/routes/eig.js, packages/backend/src/services/DemandeSejour.js, packages/backend/src/services/eig.js, packages/frontend-usagers/src/components/DS/Eigs.vue, packages/frontend-usagers/src/components/EIG/SelectionSejour.vue, packages/frontend-usagers/src/pages/demande-sejour/[[demandeId]].vue, packages/frontend-usagers/src/pages/eig/liste.vue, packages/frontend-usagers/src/stores/eig.js, packages/frontend-usagers/src/utils/eig.js
https://www.loom.com/share/1fad240c28a8404481fd5e365d980435
=> feat(eig-fo): eig dans la fiche sejour

packages/frontend-bo/src/components/utils/DisplayInput.vue
correction of sentry https://sentry.fabrique.social.gouv.fr/organizations/incubateur/issues/162071/?environment=production&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=14d&stream_index=0
=> fix(organisme-bo): check null for formatter type

packages/backend/src/app.js, packages/backend/src/controllers/eig/delete.js, packages/backend/src/controllers/eig/index.js, packages/backend/src/middlewares/can-update-or-delete-eig.js, packages/backend/src/routes/eig.js, packages/backend/src/services/eig.js, packages/frontend-bo/src/components/demandes-sejour/liste.vue, packages/frontend-bo/src/pages/sejours/index.vue, packages/frontend-usagers/src/components/DS/Eigs.vue, packages/frontend-usagers/src/pages/demande-sejour/[[demandeId]].vue, packages/frontend-usagers/src/pages/eig/liste.vue, packages/frontend-usagers/src/stores/eig.js, packages/frontend-usagers/src/utils/eig.js, packages/shared/src/components/ValidationModal.vue, packages/shared/src/components/index.js
https://www.loom.com/share/ac98ba6359464c24911ec5df73b86460
remarque : le boutton est maintenant une icone
=> feat(eig): delete

packages/frontend-bo/src/composables/useMenuNavItem.js
Close jira https://jira-mcas.atlassian.net/browse/VAO-491?atlOrigin=eyJpIjoiY2YyNDRkOWY5ZWZjNGVkNmJhZWE4YzhkMTcxZGMwNmUiLCJwIjoiaiJ9
=> fix(BO): wording

packages/frontend-bo/src/layouts/default.vue, packages/frontend-usagers/src/layouts/default.vue
close jira https://jira-mcas.atlassian.net/browse/VAO-566?atlOrigin=eyJpIjoiYzcyZmExOGQwMWZhNGI2M2JmZDg2YzI0NTJkNzE5ZmIiLCJwIjoiaiJ9
=> feat(layout): ajout d'un lien pour la version

packages/backend/src/services/BoUser.js
=> feat: add parent code for search in territoire

packages/backend/src/services/FoUser.js, packages/frontend-bo/src/pages/comptes/liste-organisme.vue
close jira https://jira-mcas.atlassian.net/browse/VAO-492?atlOrigin=eyJpIjoiZDI4MTk5ZmI0ZGU1NGQyMmFkMTZhZTcyN2FjZWQwZDQiLCJwIjoiaiJ9
=> feat(bo-organisateurs): improve columns and filters

packages/frontend-bo/src/pages/footer/accessibilite.vue, packages/frontend-usagers/src/pages/footer/accessibilite.vue
close jira https://jira-mcas.atlassian.net/browse/VAO-501?atlOrigin=eyJpIjoiOTg1NzY1ZDA0OWYzNDYyMmEzNTZkN2EwYzUyZGNiMjgiLCJwIjoiaiJ9
(copié collé) du lien suivant  dans https://ara.numerique.gouv.fr/declaration/pdlZ9Ooy13dg_UJ8x6WpD :
=> feat(accessibilite): maj declaration

packages/frontend-usagers/src/components/DS/hebergements-sejour-detail.vue, packages/frontend-usagers/src/components/HebergementWithSave.vue, packages/frontend-usagers/src/pages/hebergements/[[hebergementId]].vue
close jira 574 (https://jira-mcas.atlassian.net/browse/VAO-574?atlOrigin=eyJpIjoiZjI5YWEyMTdiMWFjNGFiMmEyOTZlMzIzNGE0NzkwMDEiLCJwIjoiaiJ9)
=> fix(hebergement): ajout bouton save

packages/frontend-usagers/src/components/DS/personnel.vue
=> fix(csv-usager): modification du fichier csv modèle

packages/backend/src/services/BoUser.js, packages/frontend-bo/src/components/demandes-sejour/liste.vue, packages/frontend-bo/src/pages/comptes/[[userId]].vue, packages/frontend-usagers/src/pages/demande-sejour/liste.vue, packages/shared/src/components/ValidationModal.vue
close jiras 506 et 573
https://www.loom.com/share/5a4244c3dd644f3794a3a746afaa40e3
=> feat(modal): add validation modals

packages/frontend-usagers/src/components/DS/hebergements-sejour-detail.vue
=> fix(hebergement): wording

packages/backend/src/controllers/bo-user/get-one.js, packages/backend/src/controllers/bo-user/list.js, packages/backend/src/services/BoUser.js, packages/frontend-bo/src/pages/comptes/[[userId]].vue, packages/frontend-bo/src/pages/comptes/liste.vue
- Modification de la méthode de récupération des utilisateurs BO pour ajouter le droit de modification en fonction du territoire
- Suppression du filtrage par défaut sur le territoire dans la liste des utilisateurs BO
- Blocage de la modification des utilisateurs s'ils ne sont pas dans le territoire (Affichage Consultation du compte plutôt que modification)
- Ajout du bouton "Fermer" lorsque l'on est en consultation du profil utilisateur
=> feat(comptesBO): tous comptes visible modif suivant droits VAO-542

.gitignore, packages/backend/src/services/mail/index.js, packages/backend/src/services/pdf/declaration2mois/generate.js, packages/backend/src/services/pdf/declaration8jours/generate.js
Objectif : tracer plus précisément les performances de la dépose de déclaration, notamment l'envoi de mails et la génération de pdf.
=> chore(sentry): add instrumentation to declaration 8jours and 2mois

packages/backend/src/app.js, packages/frontend-bo/src/composables/useMenuNavItem.js, packages/frontend-bo/src/middleware/redirect-eig.global.js, packages/frontend-bo/src/pages/eig/index.vue, packages/frontend-bo/src/pages/sejours/[declarationId].vue, packages/frontend-usagers/src/composables/useMenuNavItem.js, packages/frontend-usagers/src/middleware/redirect-eig.global.js, packages/frontend-usagers/src/pages/demande-sejour/[[declarationId]].vue, packages/frontend-usagers/src/pages/eig/liste.vue
Le but de cet PR est de masquer  la feature eig le temps que les dernieres questions soient résolues.
- on supprime tous les liens front end vers eig
- on empeche l'accès via url avec un middleware global
- on supprime toutes les routes backend eig
=> feat(eig): hide eig

packages/backend/src/controllers/eig/update.js, packages/frontend-usagers/src/components/EIG/SelectionSejour.vue
=> feat(eig): departement par defaut

packages/frontend-usagers/src/components/EIG/SelectionSejour.vue, packages/frontend-usagers/src/pages/eig/liste.vue, packages/shared/src/components/eig/Summary.vue
close jira 595
https://www.loom.com/share/12ce5ef321484b58abdb84a0820e03e1?sid=371a365a-9213-4846-9734-f11a492c203f
=> feat(eig): plus de details dans la visualisation

packages/backend/src/controllers/eig/create.js, packages/backend/src/controllers/eig/update.js, packages/backend/src/helpers/eig.js, packages/frontend-usagers/src/utils/eig.js
=> fix(eig): improve ds statut for eig declaration

packages/backend/src/services/eig.js, packages/frontend-bo/nuxt.config.ts, packages/frontend-bo/package.json, packages/frontend-bo/src/pages/eig/index.vue, packages/frontend-usagers/nuxt.config.ts, packages/frontend-usagers/package.json, packages/frontend-usagers/src/pages/eig/liste.vue, packages/shared/src/components/RangeDatePicker.vue, packages/shared/src/components/eig/EigTypeListe.vue, packages/shared/src/components/index.js, yarn.lock
close jira 592
https://www.loom.com/share/cf4d2cd93ed445e1ae4fb54f665a6394
on utilise vcalendar pour le datepicker  : 
https://vcalendar.io/datepicker/slot-content.html
=> feat(eig): improve eig list

packages/backend/src/controllers/eig/depose.js, packages/backend/src/controllers/eig/get-by-ds-id-admin.js, packages/backend/src/controllers/eig/mark-as-read.js, packages/backend/src/helpers/eig.js, packages/backend/src/middlewares/checkPermissionBOEIG.js, packages/backend/src/routes/eig.js, packages/backend/src/services/eig.js, packages/backend/src/services/geo/Commune.js, packages/backend/src/utils/mail.js, packages/frontend-bo/src/components/demandes-sejour/eigs.vue, packages/frontend-bo/src/pages/eig/index.vue, packages/frontend-bo/src/pages/index.vue, packages/frontend-bo/src/stores/eig.js, packages/frontend-bo/src/utils/utils-eig.js, packages/frontend-usagers/src/components/DS/Eigs.vue, packages/frontend-usagers/src/pages/eig/liste.vue, packages/migrations/src/migrations/20240917123037_add-read-by-dreets-and-ddets-to-eig.js, packages/shared/src/components/eig/EigStatusBadge.vue, packages/shared/src/components/eig/Summary.vue
close jira 596, 597.
j'ai rajouté la jira 584 : envoie d'un mail au reponsable du sejour et 613 : nouveau texte des mails qui s'inseraient bien dans cette PR
loom : https://www.loom.com/share/a9b5d74d611248fbae2ffecb1442ba15?sid=379a4e6b-9ec0-4f92-b95d-3307c227fbb9
**Remarque :** j'utilise le service commune de geo qui semble etre un pur copié collé du SIHONO : les nom de colonnes ne sont pas les bon, j'ai corrigé ca, a priori, on utilisait ce service nul par ailleurs
=> feat(eig): differentiate read by ddets and dreets

packages/backend/src/helpers/eig.js, packages/backend/src/schemas/eig.js, packages/backend/src/utils/mail.js, packages/frontend-bo/src/pages/eig/index.vue, packages/frontend-usagers/src/components/EIG/Recap.vue, packages/frontend-usagers/src/components/EIG/RenseignementsGeneraux.vue, packages/frontend-usagers/src/components/EIG/SelectionSejour.vue, packages/frontend-usagers/src/components/EIG/Type.vue, packages/migrations/src/migrations/20240925083938_add-is-active-to-eig-type.js, packages/shared/src/components/eig/Summary.vue, packages/shared/src/models/eig.js
PR de type +gestion des suppression de type d'eig
=> fix: some typo +remove a type

packages/frontend-bo/src/components/demandes-sejour/liste.vue
Correction de la disparition du filtre statut sur la liste de séjours côté BO
=> fix(BO): filtre statut liste sejour 658

packages/backend/src/controllers/fo-user/getExtract.js, packages/backend/src/controllers/fo-user/index.js, packages/backend/src/routes/fo-user.js, packages/backend/src/services/FoUser.js, packages/frontend-bo/src/pages/organismes/[[organismeId]].vue, packages/frontend-bo/src/stores/user.js
Sur le BackOffice : 
- Ajout d'un bouton d'extraction csv de la liste des comptes de l'organisme
=> feat(BO): csv comptes organismes 632

packages/frontend-usagers/src/components/DS/hebergements-sejour-detail.vue
=> fix(fo-ds): bug de reset de la date lors de selection d un hebergement

packages/frontend-bo/src/pages/organismes/liste.vue
=> feat(bo-organismes): wording

packages/backend/src/services/pdf/parts/InformationsPersonnel8jours.js
=> feat(cerfa): modif wording:

packages/frontend-bo/src/components/user/Compte.vue
=> feat(bo): modif libelle page utilisateur

packages/frontend-usagers/src/components/organisme/personne-morale.vue, packages/frontend-usagers/src/stores/organisme.js
Ajout de la liste des comptes qui ont le même siret pour les personnes morales sur la fiche organisateur
=> feat(fo): liste comptes même organisme 641

packages/backend/src/controllers/demandeSejour/getExtractHebergement.js, packages/backend/src/controllers/demandeSejour/index.js, packages/backend/src/controllers/hebergement/getExtract.js, packages/backend/src/controllers/hebergement/index.js, packages/backend/src/routes/hebergement.js, packages/backend/src/routes/sejour.js, packages/frontend-bo/src/components/hebergements/Lies-a-des-sejours.vue, packages/frontend-bo/src/components/hebergements/Tous.vue, packages/frontend-bo/src/stores/demande-sejour.js, packages/frontend-bo/src/stores/hebergement.js
Côté BO
- Ajout de l'export csv des hébergements
- Ajout de l'export csv des hébergements par séjour
=> feat(bo): csv hergement et herbergement sejour 579

packages/backend/src/controllers/bo-user/getExtract.js, packages/backend/src/services/BoUser.js
Ajout dans l'export CSV des comptes BO :
- Suppression de territoire
- Ajout de "compétence" pour le type de compétence, Nationale, Régionale ou Départementale
- Ajout de la colonne Région (vide si autre que région)
- Ajout de la colonne Département (vide si autre que département)
=> feat(BO): ajout colonnes dep reg dans csv 639

packages/backend/src/services/BoUser.js, packages/frontend-bo/src/components/user/Compte.vue, packages/migrations/src/migrations/20241010143818_back.users__add_dates.js
Ajout d'informations sur les comptes BO visible par le profil national
Date de création
Date d'activation
Date de dernière connexion
Date de désactivation
=> feat(comptesBO): ajout infos dates user nat 630

packages/backend/src/crons/demandes-sejours/updateStatutDS.js
Ajout de deux lignes dans l'historique du séjour au moment de l'abandon.
=> feat(cron): historique abandon DS 608

packages/frontend-bo/src/components/demandes-sejour/liste.vue, packages/frontend-bo/src/pages/index.vue, packages/shared/src/components/CardNumber.vue, packages/shared/src/components/CardsNumber.vue
close jira 648
https://github.com/SocialGouv/vao/pull/539#issue-2575927068
=> feat(bo-ds): improve ds list

packages/frontend-bo/src/components/user/Compte.vue, packages/frontend-bo/src/layouts/default.vue, packages/frontend-bo/src/utils/bo-user.js
=> feat(bo-comptes): refacto

packages/backend/src/services/BoUser.js, packages/frontend-bo/src/pages/comptes/liste.vue
=> feat(bo-comptes): better filters

packages/backend/src/controllers/fo-user/list.js, packages/backend/src/routes/fo-user.js, packages/frontend-bo/src/stores/user.js, packages/frontend-usagers/src/stores/organisme.js
Modification des routes sur le controller fo-user pour avoir des routes spécifiques coté BO et FUsager
Le chargement de la liste plantait car il testait le cookie de session jwt du BO
=> fix(list-fo-user): pb chargement list util d'un org côté FUsager

packages/backend/src/crons/demandes-sejours/notifyRappelActionsBO.js
Correction texte et lien mail FUsager + mise en gras de la seconde entête
=> fix(mail-auto): correction text mail 611

packages/backend/src/controllers/demandeSejour/getExtractHebergement.js, packages/backend/src/controllers/hebergement/getExtract.js
[Ajout email sur extraction csv des hébergements et des hébergement liés à un séjour](https://github.com/SocialGouv/vao/pull/587)
=> feat(bo-csv-hebergement: ajout colonne email 579

packages/backend/src/controllers/fo-user/getExtract.js, packages/backend/src/services/FoUser.js
Ajout de la dernière date de connexion des utilisateur FUsager dans l'export des utilisateurs par organisme
=> feat(fo-csv-fo-user): ajout date dernière connexion 632

packages/frontend-bo/src/components/demandes-sejour/liste.vue, packages/frontend-bo/src/components/utils/DisplayInput.vue
close jira #707.
Le probleme de lenteur semblait venir d'une double boucle qui recalculait des formeteurs pour chaque ligne du tableau, alors que ces formatteur sont constant. En sortant ce bout de code, les performances ont a priori nettement meilleures
=> fix(bo-ds): optimisation

packages/backend/src/controllers/organisme/update.js, packages/backend/src/routes/__tests__/organisme/update.test.js, packages/backend/src/services/Organisme.js
close jira #285. https://jira-mcas.atlassian.net/browse/VAO-285?atlOrigin=eyJpIjoiNWZmOTBiMDdjZTY2NGFmNTg1NTA3MGVkYzBmNThkMmQiLCJwIjoiaiJ9
voir le ticket pour les details
=> fix(organisme): impossible to duplicate organisms

packages/backend/src/controllers/organisme/getExtract.js
Correction du compteur séjour en cours sur l'extraction CSV des organismes
=> fix(csv-organisme): correction compteur séjour en cours 632

packages/backend/src/middlewares/checkPermissionBODeclarationSejourUpdate.js, packages/frontend-bo/src/components/demandes-sejour/Actions.vue
Corrections multiples sur les actions d'une déclaration
=> fix(bo): erreurs sur validation refus modif decla sejour

packages/frontend-bo/src/pages/territoires/liste.vue
Ajout de deux colonnes manquantes sur le liste des territoires
- Boite fonctionnelle
- Téléphone
=> feat(BO): add columns list territoire 751

packages/frontend-usagers/src/components/DS/personnel.vue, packages/shared/src/components/Table/TableFull.vue
Fix : La modification d'un personnel sur déclaration séjour n'était pas pris en compte
Fix : Remise en place du scrool horizontal pour accéder au bouton "supprimer"
=> fix(personnel): fusager suppr et modif personnel 767 766

packages/backend/src/controllers/territoire/list.js, packages/backend/src/helpers/__tests__/queryParams.test.js, packages/backend/src/helpers/queryParams.js, packages/backend/src/services/Territoire.js, packages/frontend-bo/src/components/demandes-sejour/DefaultTable.vue, packages/frontend-bo/src/components/territoires/DefaultTable.vue, packages/frontend-bo/src/components/territoires/DefaultTableFilters.vue, packages/frontend-bo/src/pages/territoires/liste.vue, packages/frontend-bo/src/stores/territoire.js
- Ajout filtre sur le nom du territoire
- Intégration tableau DSFRV2 et filtres
- Ajout des params vers route backend et ajout calcul total + pagination
=> feat(bo): list territoires filter and dsfrV2 760

packages/frontend-bo/src/pages/comptes/liste-organisme.vue
=> feat(dsfr-table): pour compte organisateurs

packages/backend/src/crons/demandes-sejours/notifyRappelActionsBO.js
Agrégation des email utilisateurs et suppression des doublons avec les emails des responsables de séjour.
Evite les envois multiples pour un même destinataire
=> fix(cron): agregation des mails et suppression des doublons 776

packages/frontend-bo/src/utils/display-input.js
Ajout nom de naissance sur la fiche organisme BO
Renommage du nom en nom d'usage
=> feat(BO): organisme ajout nom naissance 721

packages/backend/src/helpers/org-type.js, packages/backend/src/services/Organisme.js, packages/backend/src/services/organisme/PersonneMorale.js, packages/backend/src/services/organisme/PersonnePhysique.js, packages/backend/src/services/organisme/ProtocoleSanitaire.js, packages/backend/src/services/organisme/ProtocoleTransport.js, packages/migrations/src/migrations/20241205172420_organisme-refacto.js
Refacto Organisme 1/3
Mise en place du modèle de données
Mise en place de la copie des données existantes (reprise)
Mise en place des services en plus de l'écriture actuelle dans les nouvelles tables
=> feat(organsime): refacto 1 sur 3 770

packages/backend/src/helpers/org-part.js, packages/backend/src/helpers/org-type.js, packages/backend/src/services/Organisme.js, packages/backend/src/services/organisme/PersonneMorale.js, packages/backend/src/services/organisme/ProtocoleSanitaire.js, packages/backend/src/services/organisme/ProtocoleTransport.js
fix erreur command insert creation personne morale
fix si undefined ==> erreur .length : mise à jour de valeur null par défaut si vide.
=> fix(organisme): create organisme error 770

packages/backend/src/controllers/hebergement/get.js, packages/backend/src/helpers/__tests__/queryParams.test.js, packages/backend/src/helpers/queryParams.js, packages/backend/src/services/hebergement/Hebergement.js, packages/frontend-usagers/src/components/hebergements/HebergementStatusBadge.vue, packages/frontend-usagers/src/components/hebergements/filters.vue, packages/frontend-usagers/src/components/hebergements/liste.vue, packages/frontend-usagers/src/pages/hebergements/liste.vue, packages/frontend-usagers/src/stores/hebergement.js, packages/frontend-usagers/src/utils/hebergements.js
Refacto liste hébergement DSFRV2 côté Front-Usagers
=> feat(fusager): refacto tableau hébergement 794

packages/backend/src/services/Organisme.js, packages/backend/src/services/organisme/PersonneMorale.js, packages/backend/src/services/organisme/PersonnePhysique.js, packages/backend/src/services/organisme/ProtocoleSanitaire.js, packages/backend/src/services/organisme/ProtocoleTransport.js
Correction de l'erreur lors du responsable legal vide
Ajout d'une securité sur l'établisement secondiare
Remontée de la transaction create et update au niveau de l'organisme pour rollback de tout en cas d'erreur.
=> fix(fusager): organisme refacto transaction pb resp legal 770

packages/backend/src/services/hebergement/Hebergement.js, packages/frontend-usagers/src/components/hebergements/liste.vue
Correction d'un effet de bord suite à un renommage maladroit de id => hebergementId au niveau du service hébergement
=> fix(fusager): changement correction effet de bord DS hebergement 794

packages/backend/src/utils/regex.js, packages/frontend-bo/src/pages/connexion/mot-de-passe-oublie.vue, packages/frontend-bo/src/utils/regex.js, packages/frontend-usagers/src/utils/regex.js, packages/shared/src/utils/regex.js
=> fix(email): fix regex

packages/backend/src/services/Organisme.js, packages/frontend-bo/src/components/organismes/warning-non-agree.vue, packages/frontend-bo/src/pages/organismes/[[organismeId]].vue, packages/frontend-bo/src/pages/sejours/[declarationId].vue, packages/frontend-bo/src/stores/organisme.js
=> feat(organisme): alerte quand organisme plus agréé

packages/backend/src/services/hebergement/Hebergement.js, packages/frontend-usagers/src/components/DS/prestataire-detail.vue, packages/frontend-usagers/src/components/HebergementWithSave.vue, packages/frontend-usagers/src/components/address/search-address-municipality.vue, packages/frontend-usagers/src/components/address/search-address.vue, packages/frontend-usagers/src/components/organisme/personne-physique.vue, packages/frontend-usagers/src/components/personne.vue
close jira 562
https://www.loom.com/share/9e872293f0eb4204a5e9b2c8ae89f6fb
=> feat(adresse): manage not found addresses

packages/frontend-usagers/src/pages/demande-sejour/[[declarationId]].vue
Close #808
un `.value` manquait
=> fix(accessiblite): fix meta title

packages/backend/src/services/hebergement/Hebergement.js, packages/frontend-usagers/src/components/hebergements/filters.vue, packages/frontend-usagers/src/components/hebergements/liste.vue, packages/frontend-usagers/src/utils/hebergements.js
Ajout du filtre sur les statuts des hébergements côté FUsager
=> feat(fusager): hebergement add filter statuts 793

packages/frontend-usagers/src/components/address/search-address-municipality.vue
Close #562
Better ux for manual choose of adress : now
- choose street number
- chosse srtreet name
- choose postal code
https://www.loom.com/share/62651f3cecfb44d6a1533cbbaeabec8f
=> feat(hebergement): better ux for manual adresse

packages/frontend-bo/src/components/organismes/warning-non-agree.vue
Close #733
on eneleve la date moche 
devient
=> fix(warning): display date

packages/backend/src/services/hebergement/Hebergement.js, packages/frontend-usagers/src/utils/hebergements.js
Close #
tickets liés : 835
- Correction du filtre statut dans la liste des hébergement sur le Front Usager.
- Correction par effet de bord de la liste des hébergements que l'on ajoute dans une DS
=> fix(fusager): hebergement modif filtre pour débloquer liste DS 835

.talismanrc, packages/backend/src/controllers/bo-user/create.js, packages/backend/src/controllers/eig/create.js, packages/backend/src/helpers/tracking.js, packages/backend/src/middlewares/trackBoUser.js, packages/backend/src/middlewares/trackEig.js, packages/backend/src/middlewares/trackFoUser.js, packages/backend/src/routes/bo-user.js, packages/backend/src/routes/eig.js, packages/backend/src/routes/user.js, packages/backend/src/services/BoUser.js, packages/backend/src/services/Tracking.js, packages/backend/src/services/User.js, packages/backend/src/services/eig.js, packages/frontend-bo/src/components/user/Compte.vue, packages/migrations/package.json, packages/migrations/src/migrations/20250130132041_add_tracking_table.js
=> feat(historic): add historic in app

package-lock.json, package.json, yarn.lock
=> feat(is-ci): remove deps

package-lock.json, packages/backend/package.json, packages/frontend-bo/package.json, packages/frontend-usagers/package.json, packages/shared/package.json, yarn.lock
=> feat(versions): up dsfr, supertests

packages/backend/package.json, yarn.lock
=> fix(sentry): bump sentry version to match node

packages/backend/package.json, yarn.lock
=> Revert "fix(sentry): bump sentry version to match node"

package-lock.json, packages/backend/package.json, packages/frontend-bo/package.json, packages/frontend-usagers/package.json, packages/shared/package.json, yarn.lock
=> Revert "feat(versions): up dsfr, supertests"

packages/frontend-bo/src/components/hebergements/Tous.vue
=> fix(bo): liste hébergement adresse disparue 834

packages/backend/package.json, yarn.lock
=> feat(supertest): upgrade to v7

packages/frontend-bo/package.json, packages/frontend-usagers/package.json, packages/shared/package.json, yarn.lock
=> feat(dsfr): upgrade to 1.13

packages/backend/package.json, yarn.lock
=> feat(helmet): try upgrade 8.0

docker-compose.prod.yaml, docker-compose.yaml, docker/dev-create-bucket/Dockerfile
=> feat(maildev,alpin): upgrade versions

packages/frontend-bo/package.json, packages/frontend-usagers/package.json
=> feat(sentry/vue): upgrade versions

packages/frontend-bo/src/pages/territoires/[[territoireId]].vue, packages/frontend-usagers/src/components/DS/hebergements-sejour-detail.vue, yarn.lock
=> feat(wording): wording

packages/backend/src/app.js, packages/frontend-bo/package.json, packages/frontend-usagers/package.json, yarn.lock
=> feat(nuxt): upgrade versions

packages/backend/src/services/Territoire.js, packages/backend/src/services/hebergement/Hebergement.js
=> fix(hebergement/territoire): fix hebergement/territoire sort

packages/frontend-bo/package.json, packages/frontend-usagers/package.json, packages/shared/package.json, yarn.lock
=> feat(dsfr-toaster): update versions

packages/frontend-usagers/src/components/DS/informations-generales.vue
Close #
Ajout d'un message d'information sur la DS M-2 (Création / Brouillon / M-2 à modifier)
=> feat(fusager): ds-2m ajout info réglementaire 156

packages/backend/src/controllers/hebergement/desactivate.js, packages/backend/src/controllers/hebergement/index.js, packages/backend/src/controllers/hebergement/reactivate, packages/backend/src/controllers/hebergement/update.js, packages/backend/src/middlewares/checkPermissionHebergementSiegeSocial.js, packages/backend/src/middlewares/checkStatutHebergement.js, packages/backend/src/routes/__tests__/hebergement/desactivate.test.js, packages/backend/src/routes/__tests__/hebergement/reactivate.test.js, packages/backend/src/routes/__tests__/hebergement/update.test.js, packages/backend/src/routes/hebergement.js, packages/backend/src/services/Organisme.js, packages/backend/src/services/hebergement/Hebergement.js, packages/frontend-usagers/src/components/hebergements/liste.vue, packages/frontend-usagers/src/pages/hebergements/[[hebergementId]].vue, packages/frontend-usagers/src/stores/hebergement.js, packages/shared/src/components/Hebergement.vue, yarn.lock
Close #
tickets liés : 663 et 837
côté FUsagers : 
Sur liste hébergement
- Ajout du bouton désactiver un hébergement qui est actif dont on est le siège social (ou personne physique)
- Ajout du bouton réactiver un hébergement qui est désactivé dont on est le siège social (ou personne physique)
Idem sur la fiche hébergement avec les mêmes conditions.
Création d'un hébergement 
- Depuis une DS ou depuis la liste des hébergements
=> feat(fusager): hébergement desactivation et reactivation 663-837

packages/backend/src/services/organisme/ProtocoleSanitaire.js, packages/backend/src/services/organisme/ProtocoleTransport.js
Close #
tickets liés : 841
Changement de la manière de récupérer les fichiers pour les protocoles sanitaires et protocoles de tranports
On passe désormais par les fonctions qui utilisent le user vao_doc plutôt qu'un accès direct dans doc.documents qui génère une erreur  d'accès denied au schema doc 
=> fix(organisme): récupération des files des protocoles via vao_doc 841

packages/backend/src/helpers/queryParams.js, packages/backend/src/services/Organisme.js, packages/frontend-bo/src/components/organismes/liste.vue
=> feat: add sort name on organismes

packages/frontend-usagers/src/components/organisme/etablissements-secondaires.vue
=> fix(fusager-etab-sec): correction du bouton action disparu 872

packages/frontend-bo/src/pages/comptes/liste-organisme.vue
=> feat(bo): wording list comptes organisateurs 862

packages/backend/src/services/Organisme.js
=> fix(fusager): remonte agrement siege social creation

packages/frontend-usagers/src/pages/connexion/index.vue
=> add fix sur v17

packages/frontend-usagers/src/components/demande-sejour/liste.vue
=> fix(fusager): label dep instruc non visible liste message 852

packages/backend/src/helpers/queryParams.js, packages/backend/src/services/Organisme.js, packages/frontend-bo/src/components/organismes/liste.vue
=> fix(bo): list org correction tris et filtres 888

packages/backend/src/helpers/__tests__/queryParams.test.js
Update des tests qureryParams suite à correction des tris.
=> fix(tests): tests queryParams changes

packages/frontend-usagers/src/composables/useMenuNavItem.js
Fix problème de redirection sur le reset password
Effet de bord du refresh du menu déclaration de séjour suite à un appel du store organisme avec un utilisateur hors connexion non traité
=> fix(fusager): reinit password redirect connexion

packages/backend/src/controllers/siret/get.js, packages/backend/src/services/Organisme.js, packages/frontend-bo/src/components/organismes/liste.vue
tickets liés : 889
Affichage du nom de la personne physique (nom de naissance lorsque le nom d'usage n'est pas renseigné)
=> fix(bo): liste organisme nom usage pp 889

packages/backend/src/controllers/organisme/post.js, packages/backend/src/middlewares/checkPermissionBODeclarationSejour.js, packages/backend/src/routes/__tests__/organisme/finalize.test.js, packages/backend/src/services/organisme/PersonneMorale.js, packages/frontend-bo/src/pages/footer/accessibilite.vue, packages/frontend-usagers/src/pages/footer/accessibilite.vue, packages/frontend-usagers/src/pages/hebergements/[[hebergementId]].vue
884
Mise à jour de la déclaration d'accessibilité Front-Usagers et Back-Office
=> feat(accessibilite): mise à jour page description rgaa 884

.kontinuous/env/prod/values.yaml
=> fix(ingres): fix for external api ingres

packages/backend/src/controllers/bo-user/getExtract.js, packages/backend/src/controllers/demandeSejour/getExtract.js, packages/backend/src/controllers/demandeSejour/getExtractFO.js, packages/backend/src/controllers/demandeSejour/getExtractHebergement.js, packages/backend/src/controllers/demandeSejour/index.js, packages/backend/src/controllers/fo-user/getExtract.js, packages/backend/src/controllers/hebergement/getExtract.js, packages/backend/src/controllers/organisme/getListeExtract.js, packages/backend/src/routes/sejour.js, packages/backend/src/services/DemandeSejour.js, packages/backend/src/utils/csv.js, packages/frontend-usagers/src/components/demande-sejour/table.vue, packages/frontend-usagers/src/components/demande-sejour/tableFilters.vue, packages/frontend-usagers/src/stores/demande-sejour.js, packages/frontend-usagers/src/utils/csv.js
741
Les autres Csv (mise en commun de fonctionnalité)
=> feat(fusager): extract csv demande sejour 741

packages/frontend-usagers/src/components/organisme/agrement.vue, packages/frontend-usagers/src/components/organisme/synthese.vue, packages/frontend-usagers/src/pages/organisme/[[organismeId]].vue
=> fix(fusager) download file agrement 913

packages/migrations/src/migrations/20250402133230_add_siret_to_user.js
=> fix: missing migration file

packages/backend/src/controllers/demandeSejour/depose.js, packages/backend/src/controllers/demandeSejour/update.js, packages/backend/src/helpers/tracking.js, packages/backend/src/middlewares/can-update-ds.js, packages/backend/src/middlewares/trackDemandeSejour.js, packages/backend/src/routes/sejour.js, packages/backend/src/services/DemandeSejour.js, packages/backend/src/utils/mail.js, packages/frontend-usagers/src/components/DS/informations-personnel.vue, packages/frontend-usagers/src/components/DS/informations-vacanciers.vue, packages/frontend-usagers/src/components/DS/personnel.vue, packages/frontend-usagers/src/pages/demande-sejour/[[declarationId]].vue
tickets liés : 724
Mise à jour des données dans un autre statut (à modifier 8j : Brouillon)
=> feat(fusage): modif vacancier personnel j8 724

packages/backend/src/controllers/fo-user/getByOrganisme.js, packages/backend/src/controllers/fo-user/getOne.js, packages/backend/src/controllers/fo-user/index.js, packages/backend/src/controllers/fo-user/update-roles.js, packages/backend/src/middlewares/checkPermissionFoRole.js, packages/backend/src/routes/fo-user.js, packages/backend/src/services/FoUser.js, packages/frontend-usagers/src/assets/css/main.css, packages/frontend-usagers/src/components/user/Compte.vue, packages/frontend-usagers/src/components/user/UserStatusBadge.vue, packages/frontend-usagers/src/components/user/liste.vue, packages/frontend-usagers/src/components/user/listeFilters.vue, packages/frontend-usagers/src/composables/useMenuNavItem.js, packages/frontend-usagers/src/pages/comptes/[[userId]].vue, packages/frontend-usagers/src/pages/utilisateurs/liste.vue, packages/frontend-usagers/src/stores/user.js, packages/frontend-usagers/src/utils/display-input.js, packages/frontend-usagers/src/utils/fo-user.js, packages/shared/src/components/DisplayInput.vue, packages/shared/src/components/index.js
832 - 871 - 867
Ajout d'une liste d'utilisateurs lié à l'OVA (Siege social voit tout le monde, établissement secondaire ne se voit que lui)
Création d'une fiche pour chaque utilisateur avec la possibilité de modifié les droits EIG (seul une personne du même organisme peut modifier les droits s'il a lui même les droits Ecriture EIG sur les EIG
Pour le moment cela n'intègre pas la validation d'un compte créé pour lequel l'organisme siège social serait valideur. J'ajuste les tickets en conséquence
=> feat(fusager): liste utilisateurs 832-871-867

packages/backend/src/controllers/authentication/email/login.js, packages/backend/src/controllers/authentication/email/validate.js, packages/backend/src/controllers/siret/get.js, packages/backend/src/services/Insee.js, packages/backend/src/services/Territoire.js, packages/backend/src/services/User.js, packages/backend/src/utils/mail.js, packages/frontend-usagers/src/components/connexion/email/validateToken.client.vue, packages/frontend-usagers/src/pages/connexion/enregistrement.vue, yarn.lock
=> feat: change way to register new account, send mail dress

packages/backend/src/middlewares/checkPermissionBoForFoStatus.js, packages/backend/src/routes/fo-user.js
=> feat: create middleware to access to status

packages/frontend-bo/src/components/user-fo/liste.vue
=> fix: fix blink when displaying users to validate

packages/frontend-usagers/src/components/connexion/email/validateToken.client.vue
=> fix: message when confirm mail

packages/frontend-usagers/src/pages/eig/liste.vue, packages/frontend-usagers/src/stores/eig.js, packages/frontend-usagers/src/utils/eig.js
932
Fix d'une erreur 500
"getActivePinia()" was called but there was no active Pinia. Are you trying to use a store before calling "app.use(pinia)"?
@http://localhost:3000/_nuxt/utils/eig.js:7:19
=> fix(fusager): erreur 500 lien mail sur DS 932

packages/frontend-usagers/src/components/organisme/personne-morale.vue, packages/frontend-usagers/src/components/organisme/personne-physique.vue
Permet de mettre par défaut le siret de l'utilisateur lorsqu'il a validé son compte. Le reste du process suit automatiiquement.
=> feat(fusager): fix siret by default

packages/frontend-bo/src/composables/useMenuNavItem.js, packages/frontend-bo/src/pages/connexion/index.vue, packages/migrations/start.sh
=> fix: login set service competent

packages/frontend-bo/src/components/hebergements/Table.vue
=> fix: fix display of dateSejour

packages/backend/src/controllers/fo-user/update-status.js, packages/backend/src/middlewares/checkPermissionFOForUpdateStatusFo.js, packages/backend/src/routes/fo-user.js, packages/backend/src/services/FoUser.js, packages/backend/src/utils/mail.js, packages/frontend-usagers/src/assets/css/main.css, packages/frontend-usagers/src/components/user/liste.vue, packages/frontend-usagers/src/stores/user.js, packages/shared/src/components/users/UserStatusBadge.vue
Tickets liés
858 - 838 
Description 
Ajout de la validation ou le refus par l'OVA de la création des comptes.
=> feat(fusager): valid refuses new account ova 858

packages/backend/src/controllers/siret/get.js
933
Correction, erreur sur appel siret personnes physiques
=> fix(fusager): error appel siret pers phys 933

packages/backend/src/controllers/siret/get.js, packages/backend/src/services/Insee.js, packages/frontend-usagers/src/components/organisme/personne-morale.vue
Ticket 933 suite
Corrections pour la création personne morale
Plusieurs problèmes cumulés.
=> fix(fusager): error create org personne morale 933

packages/backend/src/controllers/authentication/email/login.js, packages/frontend-usagers/src/pages/connexion/index.vue
=> feat(fusager): blocage compte à la connexion 940

packages/frontend-usagers/src/components/connexion/email/validateToken.client.vue, packages/frontend-usagers/src/pages/connexion/enregistrement.vue
Wording 909 931 et text sur validation mail (pas de ticket)
=> feat(fusager): wording 909 931

packages/shared/src/components/Chat.vue
=> feat(fusager): messagerie donnees sensible 939

packages/backend/src/utils/mail.js, packages/frontend-usagers/src/components/EIG/Recap.vue, packages/frontend-usagers/src/components/EIG/SelectionSejour.vue, packages/frontend-usagers/src/stores/eig.js
Wording et correction d'appel de fonction.
Ajout import config pour le téléchargement du fichier EIG
=> fix(eig): wording et droits Eig 892-910

packages/backend/src/controllers/authentication/email/validate.js, packages/backend/src/middlewares/trackDemandeSejour.js, packages/backend/src/services/FoUser.js, packages/frontend-bo/src/pages/hebergements.vue
811
problème d'envoi de mail vers l'OVA valideur à la validation du courriel.
2 problèmes : 
- La requête ne revoyait pas le bon mail
- L'objet était mal mappé pour la liste des mails.
- Suppression de console.log qui trainaient
=> fix(fusager): mail à l'OVA pour validation compte 811

packages/frontend-usagers/src/utils/DeclarationSejour.js
Correctif visibilité du personnel sur les séjours en cours.
=> fix(fusager): visibilité du personnel pour les séjours en cours 724

packages/backend/src/utils/mail.js
859 947
Wording et corrections : Lien vers l'application + Signature (undefined)
=> fix(fusager): wording et lien vers appli et signature 859 947

packages/backend/src/services/FoUser.js, packages/frontend-usagers/src/components/user/liste.vue
=> fix(fusager): correction tri et ajout colonne 832

packages/frontend-usagers/src/components/user/Compte.vue, packages/frontend-usagers/src/utils/display-input.js
Complétion du ticket 871 (statut et organisme (principal ou secondaire) manquants.
=> fix(fusager): completion fiche utilisateur 871

packages/backend/src/controllers/organisme/post.js
865
Affectation par défaut du premier droit EIG Lecture écriture à la création d'un organisme
Personne morale : Siege social
Personne physique : D'office
=> feat(fusager): affecte premier droit Eig PP PM SiegeSocial 865

packages/frontend-bo/src/pages/eig/[eigId].vue
892
Ajout du paramètre file dans l'appel de synthèse sinon le fichier ne s'affiche pas côté BO
=> fix(bo): Eig add missing file 892

packages/backend/src/controllers/eig/get-total-to-read.js, packages/backend/src/controllers/eig/index.js, packages/backend/src/routes/eig.js, packages/backend/src/services/eig.js, packages/frontend-bo/src/composables/useMenuNavItem.js, packages/frontend-bo/src/pages/index.vue, packages/frontend-bo/src/stores/eig.js
963
Ajout d'un indicateur permettant de connaitre le nombre d'EIG à traiter (non lus) côté BO
=> feat(bo): EIG ajout d'un indicateur traitement à faire sur le menu 963

packages/migrations/src/migrations/20250521141942_add_default_role_front_users.js
865
Script de mise à jour des droits par défaut : 
- PM : premier utilisateur du siège social
- PP : Tout utilisateur
=> feat(fusager): attribution par défaut des droits EIG 865

packages/frontend-bo/src/pages/sejours/[declarationId]/messagerie.vue
981
Correction ouverture PJ au niveau Backoffice
=> fix(bo): open pj messagerie 981

packages/frontend-bo/src/pages/sejours/[declarationId]/messagerie.vue
=> fix(bo): erreur lors du téléchargement de la pj 978

packages/frontend-bo/src/assets/css/main.css, packages/frontend-bo/src/components/demandes-sejour/DefaultTableFilters.vue, packages/shared/src/components/DsfrMultiselectV2.vue, packages/shared/src/components/DsfrSelectV2.vue, packages/shared/src/components/index.js
Close #
tickets liés : 923 (https://jira-mcas.atlassian.net/jira/software/c/projects/VAO/boards/336/backlog?selectedIssue=VAO-923)
Amélioration UI de la barre de filtres en BO sur la page des DS
=> feat(bo): amelioration ui sur la barre de filtres (#923)

packages/frontend-usagers/src/components/DS/hebergements-sejour-detail.vue
962
Ajout du formatage de la date qui empêchait l'affichage dans le composant
=> fix(DS): affichage date dernière visite 962

package-lock.json, package.json, packages/backend/src/controllers/documents/upload.js, packages/backend/src/routes/documents.js, packages/frontend-bo/src/pages/sejours/[declarationId]/messagerie.vue, packages/frontend-usagers/src/components/DS/hebergements-sejour-detail.vue, packages/frontend-usagers/src/components/DS/hebergements-sejour.vue, packages/frontend-usagers/src/pages/demande-sejour/[[declarationId]].vue, packages/frontend-usagers/src/pages/eig/[[eigId]].vue, packages/frontend-usagers/src/pages/hebergements/[[hebergementId]].vue, packages/frontend-usagers/src/pages/organisme/[[organismeId]].vue, packages/frontend-usagers/src/stores/hebergement.js, packages/shared/src/utils/file.mjs, yarn.lock
974
- Ajout d'un contrôle plus en profondeur des fichiers PDF pour s'assurer qu'il n'y ait pas de JavaScript.
- Ajout des erreurs spécifiques et mutualisation pour uniformisation des messages d'erreur
Tous les écrans faisant de l'upload de fichier
- [X Plus de `console.log`
=> feat(secu): add JS detection in file and specify messages 974

packages/backend/src/controllers/demandeSejour/getExtractHebergement.js, packages/backend/src/controllers/hebergement/getExtract.js
946
Les deux exports CSV entrainaient une erreur 500 suite au passage DSFR V2
=> fix(bo): exportation des hébergements error 500 946

packages/shared/src/components/Chat.vue
=> fix(wording): rgpd messagerie 1009

packages/backend/src/config.js, packages/backend/src/controllers/geo/adresse.js, packages/backend/src/controllers/geo/checkApiAdresse.js, packages/backend/src/controllers/geo/index.js, packages/backend/src/controllers/siret/checkApiEntreprise.js, packages/backend/src/controllers/siret/checkApiInsee.js, packages/backend/src/controllers/siret/index.js, packages/backend/src/routes/geo.js, packages/backend/src/routes/siret.js, packages/backend/src/services/AdresseApi.js, packages/backend/src/services/Insee.js, packages/frontend-usagers/src/components/address/search-address.vue, packages/frontend-usagers/src/components/organisme/informations-generales.vue, packages/frontend-usagers/src/components/organisme/personne-morale.vue, packages/frontend-usagers/src/components/organisme/personne-physique.vue, packages/frontend-usagers/src/pages/connexion/enregistrement.vue, packages/frontend-usagers/src/stores/api.js, packages/shared/src/components/api/ApiUnavailable.vue, packages/shared/src/components/index.js, packages/shared/src/index.js, packages/shared/src/models/api.js, packages/shared/src/models/index.js
988
Mise en place d'alerte sur l'indisponibilité des API externes (Api INSEE/ Api ENTREPRISE / Api Adresse)
=> feat(external-api): warn unavailable api 988

packages/backend/src/helpers/queryParams.js, packages/backend/src/services/DemandeSejour.js, packages/frontend-bo/src/components/demandes-sejour/ListByMessage.vue
977
Tri des messages dans la liste des message
Le tri par "NON LU", "LU" et "REPONDU" ne se faisait plus.
=> feat(BO) tri des messages dans la messagerie 977

packages/frontend-usagers/src/pages/organisme/[[organismeId]].vue
https://jira-mcas.atlassian.net/jira/software/c/projects/VAO/boards/336/backlog?selectedIssue=VAO-980
=> fix(usagers): affichage mention renseigner fiche orga

packages/frontend-usagers/src/components/organisme/personne-physique.vue
Ajout du contrôle de l'API Insee au moment de la création d'un compte personne physique
=> fix(fusager): ajout de l'api indispo pour pers phys creation compte

packages/migrations/src/migrations/20250711164111_geo_update-eure-et-loire.js, yarn.lock
1019
Mise à jour en BDD du code région de l'Eure-et-Loire
=> fix(geo): update departement 28 1019

README.md
Ajout de liens vers backup et webseal
=> chrore(doc): update based readme.md

packages/backend/src/controllers/authentication/email/validate.js, packages/backend/src/middlewares/checkPermissionFOForUpdateStatusFo.js, packages/backend/src/services/FoUser.js
984
Envoie du mail de validation du compte vers l'organisme secondaire
Ajout des comptes à valider dans la liste des utilisateurs pour les organismes secondaires
=> feat(fusager): validation par etab secondaire

packages/backend/src/services/DemandeSejour.js, packages/frontend-bo/src/components/demandes-sejour/DefaultTable.vue
1028
Correction du compteur du nombre de déclaration filtré
Au passage correction du filtre sur les messagers
=> fix(bo): compteur liste DS et filtre messages declarations 1028

packages/frontend-usagers/src/composables/useMenuNavItem.js, packages/frontend-usagers/src/pages/index.vue
1004
On masque ma partie saisie de l'hébergement (menu + card) tant que la fiche organisme n'est pas complète
=> feat(fusager): mask hebergement when org not complete 1004

packages/backend/src/controllers/demandeSejour/getExtractHebergement.js, packages/backend/src/controllers/hebergement/getExtract.js, packages/backend/src/helpers/queryParams.js
1045
On lève la limite des exports sinon ça prend la pagination par défaut
=> fix(bo): export hebergement limit 1045

e2e/register-login-organisateur.spec.ts, packages/backend/src/helpers/declaration/mise-en-page.js, packages/backend/src/services/pdf/parts/Agrement.js, packages/backend/src/services/pdf/parts/FicheAnnexe.js, packages/backend/src/services/pdf/parts/InformationsGenerales.js, packages/backend/src/services/pdf/parts/InformationsPersonnel.js, packages/backend/src/services/pdf/parts/InformationsPersonnel8jours.js, packages/backend/src/services/pdf/parts/InformationsSanitaires.js, packages/backend/src/services/pdf/parts/InformationsTransport.js, packages/backend/src/services/pdf/parts/InformationsVacanciers.js, packages/backend/src/services/pdf/parts/Organisme.js, packages/backend/src/services/pdf/parts/ProjetSejour.js, packages/backend/src/services/pdf/parts/RepresentantLegaux.js, packages/backend/src/services/pdf/parts/ResponsableOrganisation.js, packages/backend/src/services/pdf/parts/Sanitaire.js, packages/backend/src/services/pdf/parts/Transport.js, packages/backend/src/services/pdf/parts/TransportHebergement.js
1031
Refacto de toute la pagination des pdf afin de pouvoir customiser
=> feat(pdf): customisation de la pagination (refacto) 1031

packages/frontend-usagers/src/components/personnes.vue
https://jira-mcas.atlassian.net/jira/software/c/projects/VAO/boards/336?issueParent=142055&selectedIssue=VAO-1139
=> fix: boutton suppr representant (rgaa) (#1139)

packages/backend/src/controllers/organisme/getListeExtract.js
1112
Formatage du numéro de siret et siren dans l'export csv organisme côté BO pour plus de lisibilité
=> feat(bo): format siret siren on csv organisme 1112

packages/backend/src/controllers/authentication/email/__tests__/register.test.js
=> chore(tests): fix linter problem

packages/frontend-bo/src/components/user/Compte.vue, packages/frontend-bo/src/pages/territoires/[[territoireId]].vue, packages/shared/src/components/Table/TableFull.vue, packages/shared/src/components/Table/TableUI.vue, packages/shared/src/components/TitleWithIcon.vue, packages/shared/src/components/index.js
https://jira-mcas.atlassian.net/jira/software/c/projects/VAO/boards/336?selectedIssue=VAO-1048
Lien maquette: https://jira-mcas.atlassian.net/jira/software/c/projects/VAO/boards/336?selectedIssue=VAO-1048#:~:text=Maquettes-,Maquettes_V2%20%2D%20VAO,-Crit%C3%A8res%20d%27acceptation
=> feat: refonte pages territoires (bo) (1048)

.talismanrc, packages/frontend-bo/src/components/eig/Synthese.vue, packages/shared/src/components/FileUpload.vue, packages/shared/src/components/TitleWithIcon.vue, packages/shared/src/components/eig/Summary.vue, packages/shared/src/components/index.js
https://jira-mcas.atlassian.net/jira/software/c/projects/VAO/boards/336?selectedIssue=VAO-1047
Refonte page EIG coté bo
Notes:
-Une icone utilisée dans la maquette n'est pas dispo dans la version dsfr utilisée > upgrade dsfr
-pas d'icone à coté d'un titre dans un tableau (dsfr)
=> feat: refonte page synthese eig (bo) (1047)

packages/shared/src/components/FileUpload.vue
1153
Correction du crash du render lorqu'il n'y a pas de fichier à afficher
=> fix(file): crash eig when empty file 1153

packages/frontend-usagers/src/pages/connexion/enregistrement.vue
https://jira-mcas.atlassian.net/browse/VAO-935?atlOrigin=eyJpIjoiYzdhYzk3MDE3MzM2NDBiNjk3YjJhNTAyNzAwYmFjMjciLCJwIjoiaiJ9
=> feat: ajout mention creation compte (front) (935)

packages/backend/src/controllers/demandeSejour/copy.js, packages/backend/src/schemas/declaration-sejour.js, packages/frontend-usagers/src/components/demande-sejour/table.vue, packages/frontend-usagers/src/utils/DeclarationSejour.js, packages/migrations/src/migrations/20250917220011_demande_sejour__libelle_100.js
=> fix: duplication DS libelle trop long (#1119)

packages/frontend-usagers/src/components/EIG/Recap.vue, packages/shared/src/components/eig/Summary.vue
https://jira-mcas.atlassian.net/jira/software/c/projects/VAO/boards/336?selectedIssue=VAO-1156
=> feat: refonte page synthese eig (fusagers) (1156)

packages/frontend-usagers/src/pages/mon-compte.vue
936
Ajout d'un message d'info sur l'écran de modification d'un compte
=> feat(fusager): add info mon compte 936

packages/frontend-usagers/src/components/SyntheseVerificationAlert.vue
https://jira-mcas.atlassian.net/jira/software/c/projects/VAO/boards/336?selectedIssue=VAO-1097
Rend la synthese DS accessible aux lecteurs d'ecrans
=> fix(rgaa): amelioration des indications dans synthese DS (#1097)

.github/workflows/lint-format-tests.yaml, sonar-project.properties
https://jira-mcas.atlassian.net/browse/VAO-813
Mise à jour des règles de coverage sonar
=> chore: 813 - update sonar coverage rules

packages/backend/src/controllers/eig/get-pdf.js, packages/backend/src/controllers/eig/index.js, packages/backend/src/routes/__tests__/eig/get-pdf.test.js, packages/backend/src/routes/eig.js, packages/backend/src/services/__tests__/pdf/eig/build.test.js, packages/backend/src/services/__tests__/pdf/eig/generate.test.js, packages/backend/src/services/pdf/eig/build.js, packages/backend/src/services/pdf/eig/generate.js, packages/frontend-bo/src/components/eig/Synthese.vue, packages/frontend-bo/src/stores/eig.js, sonar-project.properties
1043
Création d'un bouton de génération d'un PDF sur l'écran EIG côté BO
=> feat(bo): 1043 generate pdf for eig

packages/migrations/src/migrations/20251007095507_update_front_user_lastconnexion.js
1145
Creation des scripts de mise à jour de la dernière date de connexion en date limite + Script d'extraction et rollback
=> feat(cron): 1145 script maj lastconnexion avant mep

packages/frontend-usagers/src/components/DS/informations-personnel.vue, packages/frontend-usagers/src/components/DS/personnel.vue, packages/frontend-usagers/src/components/DS/synthese.vue, packages/frontend-usagers/src/components/personne.vue, packages/frontend-usagers/src/utils/informationsPersonnel.js
1124
Correction de la possibilité de transmettre une DS8J alors que l'attestation sur l'honneur du personnel n'était pas cochée, cela générait de toute façon une erreur. Mais on ne voyait pas sur l'écran de synthèse le fait qu'il y avait du personnel incomplet.
Au delà de ce correctif, passage en lecture seul des champs sur la partie synthèse qui étaient modifiables
=> fix(fusager): ds uncomplete ds8j appear complete 1124
